import test from'node:test';import assert from'node:assert/strict';import{build}from'esbuild';import{createHash}from'node:crypto';import{encodeAttribute,decodeAttribute}from'../src/asset-normal-codec-v3.ts';import type{AttributeRecipe,OctahedralAttributeRecipe}from'../src/asset-normal-codec-v3.ts';
const f=Math.fround,bytes=(a:ArrayBufferView)=>new Uint8Array(a.buffer,a.byteOffset,a.byteLength),serialize=(r:unknown)=>JSON.stringify(r,(_k,v)=>v instanceof Uint8Array?Array.from(v):v);
// Independent Float32 reference expression for the published octahedral convention.
function reference(s:number,t:number,bits:number){const scale=f(2/(2**bits-2));let y=f(f(s*scale)-1),z=f(f(t*scale)-1),x=f(f(1-Math.abs(y))-Math.abs(z)),offset=-x;if(offset<0)offset=0;y=f(y+(y<0?offset:-offset));z=f(z+(z<0?offset:-offset));const n=f(f(f(x*x)+f(y*y))+f(z*z));if(n<1e-6)return[0,0,0];const d=f(1/f(Math.sqrt(n)));return[f(x*d),f(y*d),f(z*d)]}
function fixture(bits=10,count=4096,width=3){const a=new Float32Array(count*width),words=new Uint32Array(a.buffer),max=2**bits-2;for(let i=0;i<count;i++){a.set(reference((i*17)%(max+1),(i*47)%(max+1),bits),i*width);if(width===4)words[i*4+3]=i%9===0?0x80000000:i%13===0?0x7fc00042:i%2?0x3f800000:0xbf800000}return a}
function check(a:Float32Array,width=3){const input={array:a,componentType:5126,type:width===3?'VEC3':'VEC4',count:a.length/width,normalized:false},copy=new Uint8Array(bytes(a)),r=encodeAttribute(input),out=decodeAttribute(r.recipe);assert.deepEqual(bytes(out),copy);assert.deepEqual(bytes(a),copy);assert.equal(out.constructor,Float32Array);assert.equal(serialize(r),serialize(encodeAttribute(input)));assert(r.metrics.recipeBytes<=r.metrics.baselineBytes);return r}
test('inferred octahedral grids execute exact vectors and win real payload cost',()=>{const r=check(fixture());assert.equal(r.metrics.selected,'octahedral-f32');assert.equal(r.metrics.octahedral?.bits,10);assert(r.metrics.recipeBytes<r.metrics.baselineBytes/2);for(const bits of[4,6,8,12,16])check(fixture(bits,768));});
test('tangent fourth components and sparse original-word exceptions stay exact',()=>{check(fixture(10,2048,4),4);const a=fixture(),w=new Uint32Array(a.buffer);w[33]=0x80000000;w[111]=0x7fc0abcd;w[333]=w[333]!^1;w[951]=0x7f800000;w[1311]=0x00000001;const r=check(a);assert.equal(r.metrics.selected,'octahedral-f32');assert((r.metrics.octahedral?.patchWords??0)>=5);});
test('nonunit arbitrary data, empty and unsupported types use exact fallback',()=>{let seed=123;const a=new Float32Array(6000);for(let i=0;i<a.length;i++){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;a[i]=(seed|0)/37}assert.notEqual(check(a).metrics.selected,'octahedral-f32');check(new Float32Array());const input={array:new Uint16Array([0,1,2,3]),componentType:5123,type:'SCALAR',count:4,normalized:true},r=encodeAttribute(input);assert.deepEqual(decodeAttribute(r.recipe),input.array);});
test('malicious pair extents, reserved coordinates, patch indices and counts reject',()=>{const r=check(fixture()).recipe as OctahedralAttributeRecipe;assert.equal(r.storage.kind,'octahedral-f32');if(r.storage.kind!=='octahedral-f32')return;const s=r.storage;assert.throws(()=>decodeAttribute({...r,storage:{...s,bits:1}}));assert.throws(()=>decodeAttribute({...r,storage:{...s,predictor:2}as unknown as typeof s}));assert.throws(()=>decodeAttribute({...r,count:1048577}));assert.throws(()=>decodeAttribute({...r,storage:{...s,pairs:{...s.pairs,sourceLength:1}}}));const invalid:AttributeRecipe={version:3,componentType:5126,type:'VEC3',count:1,normalized:false,storage:{kind:'octahedral-f32',bits:2,predictor:0,pairs:{codec:'raw',parameters:{version:1},sourceLength:1,data:new Uint8Array([15])}}};assert.throws(()=>decodeAttribute(invalid),/coordinate/);const patched={...invalid,storage:{...invalid.storage,pairs:{codec:'raw',parameters:{version:1},sourceLength:1,data:new Uint8Array([5])},exceptions:{codec:'raw',parameters:{version:1},sourceLength:5,data:new Uint8Array(5)}}}as AttributeRecipe;assert.throws(()=>decodeAttribute(patched),/patch/);});
test('browser and Node recipes, repeated hashes and reconstruction match',async()=>{const b=await build({entryPoints:[new URL('../src/asset-normal-codec-v3.ts',import.meta.url).pathname],bundle:true,platform:'browser',format:'esm',minify:true,write:false}),browser=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0]!.contents).toString('base64')),array=fixture(),input={array,componentType:5126,type:'VEC3',count:array.length/3,normalized:false},r=encodeAttribute(input);assert.equal(serialize(r),serialize(browser.encodeAttribute(input)));assert.deepEqual(bytes(browser.decodeAttribute(r.recipe)),bytes(array));const hashes=Array.from({length:3},()=>createHash('sha256').update(serialize(encodeAttribute(input))).digest('hex'));assert.equal(new Set(hashes).size,1);});
