import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { compileSurface, replaySurface } from '../src/asset-native-surface-v2.ts';
import type { SurfaceInput, SurfaceRecipe } from '../src/asset-native-surface-v2.ts';
function bytes(a:ArrayBufferView):Uint8Array{return new Uint8Array(a.buffer,a.byteOffset,a.byteLength)}
function check(input:SurfaceInput){const result=compileSurface(input),out=replaySurface(result.recipe);assert.deepEqual(bytes(out.positions),bytes(input.positions));assert.equal(out.indices?.constructor,input.indices?.constructor);if(input.indices)assert.deepEqual(bytes(out.indices!),bytes(input.indices));else assert.equal(out.indices,null);assert.deepEqual(out.mesh.positions,Array.from(input.positions));assert.deepEqual(out.mesh.indices,input.indices?Array.from(input.indices):Array.from({length:input.positions.length/3},(_,i)=>i));assert(result.metrics.recipeBytes<=result.metrics.residualRecipeBytes);assert.equal(JSON.stringify(compileSurface(input)),JSON.stringify(result));return result;}
let seed=0x12856aef;function next(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return seed>>>0;}
function mirroredFixture(){const vertices=64,positions=new Float32Array(vertices*6);for(let i=0;i<vertices;i++){const row=[next()/2**32*20+1,next()/2**32*20,next()/2**32*20];positions.set(row,i*3);positions.set([-row[0]!,row[1]!,row[2]!],(i+vertices)*3);}const indices:number[]=[],known=new Set<string>();while(indices.length<1800){const a=next()%vertices,b=next()%vertices,c=next()%vertices;if(new Set([a,b,c]).size!==3)continue;const key=[a,b,c].sort((a,b)=>a-b).join(',');if(known.has(key))continue;known.add(key);indices.push(a,b,c);}const source=[...indices];for(let i=0;i<source.length;i+=3)indices.push(source[i]!+vertices,source[i+2]!+vertices,source[i+1]!+vertices);return{positions,indices:new Uint16Array(indices)};}
test('native grid construction preserves every ordered index and exact coordinate',()=>{const positions=new Float32Array(32*32*3);for(let row=0;row<32;row++)for(let col=0;col<32;col++)positions.set([col*.25,row*.5,2],(row*32+col)*3);const indices:number[]=[];for(let row=0;row<31;row++)for(let col=0;col<31;col++){const a=row*32+col,b=a+32;indices.push(a,b,a+1,a+1,b,b+1)}const r=check({positions,indices:new Uint16Array(indices)});assert.equal(r.metrics.positionOperation,'grid');assert.equal(r.metrics.affineGeneratedVertices,1023);});
test('filled coplanar contours and triangle strips are executed, with exact corner order',()=>{const count=512,positions=new Float32Array((count+1)*3);positions.set([0,0,2]);for(let i=0;i<count;i++)positions.set([Math.cos(i*.01)*5,Math.sin(i*.01)*5,2],(i+1)*3);const fan:number[]=[];for(let i=1;i<count;i++)fan.push(0,i,i+1);const filled=check({positions,indices:new Uint16Array(fan)});assert.equal(filled.metrics.filledContourTriangles,count-1);assert.equal(filled.metrics.explicitResidualTriangles,0);const strip:number[]=[];for(let i=2;i<=count;i++)strip.push(i%2?i-1:i-2,i%2?i-2:i-1,i);const stripped=check({positions,indices:new Uint16Array(strip)});assert.equal(stripped.metrics.stripTriangles,count-1);});
test('generic mirrored connectivity generates source-derived counterpart triangles',()=>{const input=mirroredFixture(),r=check(input);assert.equal(r.metrics.mirroredTriangles,600);assert.equal(r.recipe.topology.kind,'operations');assert(r.metrics.recipeBytes<r.metrics.residualRecipeBytes);});
test('raw fallback retains NaN payloads, signed zeros, all index widths, and nontriangle modes',()=>{const words=new Uint32Array([0x80000000,0,0x7fc00042,0x3f800000,0,0,0,0x3f800000,0]),positions=new Float32Array(words.buffer);for(const C of[Uint8Array,Uint16Array,Uint32Array])for(const mode of[0,1,2,3,4,5,6]){const r=check({positions,indices:new C([0,1,2]),mode});assert.equal(r.recipe.positions.kind,'residual');assert.equal(r.recipe.topology.kind,'residual');}check({positions,indices:null,mode:0});check({positions:new Float32Array(),indices:new Uint8Array()});});
test('seeded arbitrary primitive fuzz and deterministic hashes',()=>{for(let trial=0;trial<35;trial++){const count=3+next()%60,positions=new Float32Array(count*3);for(let i=0;i<positions.length;i++)positions[i]=(next()%10000-5000)/8;const indices=new Uint32Array(3*(1+next()%100));for(let i=0;i<indices.length;i++)indices[i]=next()%count;check({positions,indices});}const fixture=mirroredFixture();const hashes=Array.from({length:3},()=>createHash('sha256').update(JSON.stringify(compileSurface(fixture))).digest('hex'));assert.equal(new Set(hashes).size,1);});
test('hostile recipe counts, grid seeds, payload extents and indices reject',()=>{const valid=compileSurface({positions:new Float32Array([0,0,0,1,0,0,0,1,0]),indices:new Uint16Array([0,1,2])}).recipe;assert.throws(()=>replaySurface({...valid,vertexCount:1e20}));assert.throws(()=>replaySurface({...valid,indexCount:1e20}));assert.throws(()=>replaySurface({...valid,positions:{kind:'grid',start:[0,0,0],u:[0,0,0],v:({length:1e20}as unknown as number[]),columns:2}}));assert.throws(()=>compileSurface({positions:new Float32Array([0,0,0]),indices:new Uint16Array([0,1,2])}));assert.throws(()=>replaySurface({...valid,topology:{kind:'unindexed'}}));const r=structuredClone(valid);if(r.positions.kind==='residual'){r.positions.buffer.sourceLength=1;assert.throws(()=>replaySurface(r));}});
test('browser bundle returns the identical recipe and actual native MeshData',async()=>{const bundled=await build({entryPoints:[new URL('../src/asset-native-surface-v2.ts',import.meta.url).pathname],bundle:true,format:'esm',platform:'browser',minify:true,write:false});const browser=await import('data:text/javascript;base64,'+Buffer.from(bundled.outputFiles[0]!.contents).toString('base64')),input=mirroredFixture(),node=compileSurface(input),other=browser.compileSurface(input);assert.equal(JSON.stringify(node),JSON.stringify(other));const decoded=browser.replaySurface(other.recipe);assert.deepEqual(bytes(decoded.positions),bytes(input.positions));assert.deepEqual(bytes(decoded.indices),bytes(input.indices));assert.deepEqual(Object.keys(decoded.mesh).sort(),['colours','indices','joints','positions','uvs','weights']);});
