import test from 'node:test';
import assert from 'node:assert/strict';
import {compileAsset,buildAsset,decodePackage,COMPILER_VERSION} from '../src/asset-compiler-v3.ts';
import {unpackAsset} from '../src/asset-binary-v3.ts';
const te=new TextEncoder();
async function empty(){return compileAsset({files:[{name:'empty.gltf',data:te.encode('{"asset":{"version":"2.0"}}')}],entry:'empty.gltf',mode:'lossless'})}
test('empty native scene and standalone original JSON decode without invented optional tables',async()=>{const r=await empty(),b=await buildAsset(unpackAsset(r.packageBytes));assert.deepEqual(b.scene.json,{asset:{version:'2.0'}});const original=te.encode(' {"asset":{"version":"2.0"}}\n'),d=await decodePackage(original);assert.equal(d.entry,'asset.gltf');assert.deepEqual(d.files[0]!.data,original);});
test('replay rejects unknown mode and invalid or duplicate override targets before decoding',async()=>{const r=unpackAsset((await empty()).packageBytes)as any;await assert.rejects(()=>buildAsset({...r,mode:'made-up'}),/unsupported/);await assert.rejects(()=>buildAsset({...r,images:[{image:100,recipe:{}}]}),/image override/);await assert.rejects(()=>buildAsset({...r,attributes:[{accessor:0,recipe:{}}]}),/override target/);await assert.rejects(()=>buildAsset({...r,positions:[{accessor:0,recipe:{}}]}),/override target/);});
test('preserved decode rejects incomplete containers and absent dependencies',async()=>{const header=new Uint8Array(12),v=new DataView(header.buffer);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,12,true);await assert.rejects(()=>decodePackage(header),/GLB/);await assert.rejects(()=>decodePackage(te.encode('{"asset":{"version":"2.0"},"buffers":[{"uri":"missing.bin","byteLength":1}]}')),/external resources/);});
test('aggregate preflight counts repeated image output before inflating payloads',async()=>{const r=unpackAsset((await empty()).packageBytes)as any;r.base.images=Array.from({length:8},()=>({mimeType:'image/png',data:null}));r.images=r.base.images.map((_:any,image:number)=>({image,recipe:{version:3,codec:'rgba-zlib',width:4096,height:4096,decodedLength:1,data:new Uint8Array()}}));await assert.rejects(()=>buildAsset(r),/aggregate decoded budget/);});
test('aggregate preflight counts shared per-primitive UV numeric arrays before replay',async()=>{const raw={codec:'raw',parameters:{version:1},sourceLength:12000,data:new Uint8Array()},p={mode:0,attributes:{POSITION:0,TEXCOORD_0:1}},surface={mesh:0,primitive:0,positionAccessor:0,indexAccessor:null,recipe:{version:2,vertexCount:1000,indexCount:0,indexType:0,mode:0,positions:{kind:'residual',buffer:raw},topology:{kind:'unindexed'}}};const n=5000,r:any={format:'KEEL-NATIVE-V3',compilerVersion:COMPILER_VERSION,mode:'lossless',attributes:[],positions:[],images:[],base:{descriptors:[{componentType:5126,type:'VEC3',count:1000,normalized:false},{componentType:5126,type:'VEC2',count:1000,normalized:false}],residualAccessors:[null,{...raw,sourceLength:8000}],surfaces:Array.from({length:n},(_,i)=>({...surface,primitive:i})),images:[],json:{meshes:[{primitives:Array.from({length:n},()=>p)}]}}};await assert.rejects(()=>buildAsset(r),/aggregate decoded budget/);});
