import test from 'node:test';
import assert from 'node:assert/strict';
import {quantizePositions,quantizePositionAccessors,quantizePositionAccessorsWithRecipes,quantizeBasePositions,replayQuantizedPositions} from '../src/asset-position-quantize-v3.ts';

const words=(a:Float32Array)=>Array.from(new Uint32Array(a.buffer,a.byteOffset,a.length));
function fixture(arrays:Float32Array[],primitives?:any[]) {return {format:'KEEL-NATIVE-SCENE',version:2,json:{asset:{version:'2.0'},accessors:arrays.map(a=>({componentType:5126,type:'VEC3',count:a.length/3})),meshes:[{primitives:primitives??arrays.map((_,i)=>({attributes:{POSITION:i}}))}],nodes:[{mesh:0}],scenes:[{nodes:[0]}],scene:0},sourceJson:{},accessors:arrays.map((array,i)=>({sourceIndex:i,componentType:5126,type:'VEC3',normalized:false,count:array.length/3,array})),images:[],source:{},validation:{},runtime:{}} as any;}
function cloud(count=600){const a=new Float32Array(count*3);let s=123456789;for(let i=0;i<a.length;i++){s=(Math.imul(s,1664525)+1013904223)>>>0;a[i]=(s/4294967296-.5)*(i%3+1)*17;}return a;}

test('lossless preserves every Float32 bit, including signed zero',()=>{const a=new Float32Array([-0,0,1,0,-0,2,1,2,3]);const out=quantizePositions(a,{mode:'lossless'});assert.deepEqual(words(out.positions),words(a));assert.equal(out.applied,false);assert.notEqual(out.positions,a);});
test('full-array measured displacement satisfies the absolute and relative caps',()=>{const a=cloud();const out=quantizePositions(a,{mode:'bounded-lossy',maxAbsoluteError:.02,maxRelativeError:.0005});assert(out.applied);let max=0;for(let i=0;i<a.length;i+=3)max=Math.max(max,Math.hypot(...[0,1,2].map(k=>out.positions[i+k]!-a[i+k]!)));assert.equal(max,out.maxPositionError);assert(max<=.02);assert(max<=out.boundsDiagonal*.0005);});
test('constant axes, zero extents and empty inputs never divide by zero',()=>{for(const a of [new Float32Array(),new Float32Array([-0,3,4,-0,3,4]),new Float32Array([0,0,0,1,0,0,.123456,0,0])]){const r=quantizePositions(a,{mode:'bounded-lossy',maxAbsoluteError:.01});assert(r.positions.every(Number.isFinite));assert(r.maxPositionError<=.01);}assert.deepEqual(words(quantizePositions(new Float32Array([-0,0,0,0,-0,0]),{mode:'bounded-lossy',maxAbsoluteError:1}).positions),words(new Float32Array([-0,0,0,0,-0,0])));});
test('nonfinite values and invalid budgets or precision reject',()=>{for(const v of [NaN,Infinity,-Infinity])assert.throws(()=>quantizePositions(new Float32Array([v,0,0]),{mode:'lossless'}));for(const maxAbsoluteError of [-1,NaN,Infinity])assert.throws(()=>quantizePositions(cloud(2),{mode:'bounded-lossy',maxAbsoluteError}));assert.throws(()=>quantizePositions(cloud(2),{mode:'bounded-lossy'}));assert.throws(()=>quantizePositions(cloud(2),{mode:'bounded-lossy',maxAbsoluteError:1,minBits:25}));assert.throws(()=>quantizePositions(cloud(2),{mode:'bounded-lossy',maxAbsoluteError:1,minBits:12,maxBits:8}));});
test('all primitives participate, shared positions remain shared, other arrays and metadata stay exact',()=>{const a=cloud(),b=cloud(400),normals=new Float32Array(a.length).fill(.5),asset=fixture([a,b,normals],[{attributes:{POSITION:0,NORMAL:2}},{attributes:{POSITION:1}},{attributes:{POSITION:0}}]);asset.images=[{mimeType:'image/png',data:new Uint8Array([1,2,3])}];asset.json.extras={unchanged:'metadata'};const before=structuredClone(asset.json),r=quantizePositionAccessors(asset,{mode:'bounded-lossy',maxAbsoluteError:.05});assert.equal(r.metrics.length,2);assert.equal(r.metrics[0]!.primitives.length,2);assert.deepEqual(r.asset.json,before);assert.equal(r.asset.accessors[2],asset.accessors[2]);assert.equal(r.asset.images,asset.images);assert.deepEqual(words(asset.accessors[0].array),words(a));assert(r.metrics.every(m=>m.maxPositionError<=.05));});
test('aliases in normals, morphs, weights, rig and animations protect source bits',()=>{for(const kind of ['normal','morph','skin','animation']){const asset=fixture([cloud()]);if(kind==='normal')asset.json.meshes[0].primitives[0].attributes.NORMAL=0;if(kind==='morph')asset.json.meshes[0].primitives[0].targets=[{POSITION:0}];if(kind==='skin')asset.json.skins=[{inverseBindMatrices:0,joints:[]}];if(kind==='animation')asset.json.animations=[{samplers:[{input:0,output:0}],channels:[]}];const out=quantizePositionAccessors(asset,{mode:'bounded-lossy',maxAbsoluteError:1});assert.equal(out.metrics[0]!.applied,false,kind);assert.deepEqual(words(out.asset.accessors[0]!.array as Float32Array),words(asset.accessors[0].array),kind);}});
test('opaque extensions conservatively protect possible accessor aliases',()=>{const asset=fixture([cloud()]);asset.json.extensionsUsed=['TEST_accessor_alias'];const out=quantizePositionAccessors(asset,{mode:'bounded-lossy',maxAbsoluteError:1});assert.equal(out.metrics[0]!.applied,false);});
test('compact lattice replay matches the exact measured quantized Float32 result',()=>{const asset=fixture([cloud(1200)]),r=quantizeBasePositions(asset,{maxError:.03});assert(r.report.changedAccessorIds.length>0);for(const p of r.positionRecipes){const replay=replayQuantizedPositions(p.recipe);assert.deepEqual(words(replay),words(r.normalized.accessors[p.accessor]!.array as Float32Array));assert(p.recipeBytes<p.exactPositionRecipeBytes);}for(const m of r.report.metrics)assert(m.maxPositionError<=.03);});
test('fixed source/settings produce identical recipes and Float32 bits',()=>{const asset=fixture([cloud()]),a=quantizeBasePositions(asset,{maxError:.04}),b=quantizeBasePositions(asset,{maxError:.04});assert.deepEqual(a,b);});
test('existing compact affine representation keeps exact positions if quantization costs more',()=>{const a=new Float32Array(300);for(let i=0;i<100;i++)a.set([Math.fround(i*.125),1,-3],i*3);const asset=fixture([a]),r=quantizeBasePositions(asset,{maxError:.1});assert.deepEqual(words(r.normalized.accessors[0]!.array as Float32Array),words(a));assert.equal(r.report.changedAccessorIds.length,0);});
test('invalid or corrupt lattice recipes reject',()=>{const r=quantizeBasePositions(fixture([cloud(1200)]),{maxError:.03});assert(r.positionRecipes.length);const recipe=r.positionRecipes[0]!.recipe;for(const changed of [{...recipe,vertexCount:recipe.vertexCount+1},{...recipe,bits:99},{...recipe,minimumWords:[0,0,0x7f800000]},{...recipe,codes:{...recipe.codes,data:'!'}}])assert.throws(()=>replayQuantizedPositions(changed as any));});
test('rich recipe API applies each accessor relative cap and the absolute cap together',()=>{const large=cloud(1200),small=Float32Array.from(large,v=>v*.001),asset=fixture([large,small]),options={mode:'bounded-lossy' as const,maxRelativeError:.0005,maxAbsoluteError:.02,minBits:8,maxBits:24},r=quantizePositionAccessorsWithRecipes(asset,options);assert.equal(r.report.metrics.length,2);for(const m of r.report.metrics){assert.equal(m.maxAllowedError,Math.min(m.boundsDiagonal*.0005,.02));assert(m.maxPositionError<=m.maxAllowedError);}assert(r.report.metrics[1]!.maxAllowedError<r.report.metrics[0]!.maxAllowedError);for(const p of r.positionRecipes)assert.deepEqual(words(replayQuantizedPositions(p.recipe)),words(r.normalized.accessors[p.accessor]!.array as Float32Array));assert.deepEqual(r,quantizePositionAccessorsWithRecipes(asset,options));});
test('absolute alias retains prior contract and shares rich recipe selection',()=>{const asset=fixture([cloud(1200)]),a=quantizeBasePositions(asset,{maxError:.03}),b=quantizePositionAccessorsWithRecipes(asset,{mode:'bounded-lossy',maxAbsoluteError:.03});assert.equal(a.report.maxError,.03);assert.deepEqual(a.normalized,b.normalized);assert.deepEqual(a.positionRecipes,b.positionRecipes);assert.deepEqual(a.report.metrics,b.report.metrics);assert.deepEqual(a.report.costs,b.report.costs);const exact=quantizePositionAccessorsWithRecipes(asset,{mode:'lossless',maxRelativeError:.1});assert.equal(exact.positionRecipes.length,0);assert.deepEqual(words(exact.normalized.accessors[0]!.array as Float32Array),words(asset.accessors[0].array));});
test('binary lattice payload replays the same quantized Float32 bits as legacy base64',()=>{const result=quantizeBasePositions(fixture([cloud(1200)]),{maxError:.03});assert(result.positionRecipes.length);for(const {recipe} of result.positionRecipes){assert.equal(typeof recipe.codes.data,'string');const payload=Buffer.from(recipe.codes.data as string,'base64'),padded=new Uint8Array(payload.length+8);padded.set(payload,4);const binary={...recipe,codes:{...recipe.codes,data:padded.subarray(4,4+payload.length)}};assert.deepEqual(words(replayQuantizedPositions(binary)),words(replayQuantizedPositions(recipe)));}});
test('multi-megabyte raw lattice payload works as binary and base64 without regex recursion',()=>{const payload=new Uint8Array(3*1024*1024);for(let i=0;i<payload.length;i++)payload[i]=(Math.imul(i,73)+19)&255;const recipe={kind:'quantized-lattice' as const,version:3 as const,vertexCount:payload.length/3,bits:8,minimumWords:[0,0,0],maximumWords:[0x3f800000,0x40000000,0x40400000],codes:{codec:'raw',parameters:{version:1},sourceLength:payload.length,data:payload}};const binary=replayQuantizedPositions(recipe),base64=replayQuantizedPositions({...recipe,codes:{...recipe.codes,data:Buffer.from(payload).toString('base64')}});assert.deepEqual(Buffer.from(binary.buffer),Buffer.from(base64.buffer));assert.equal(binary[0],Math.fround(payload[0]!/255));assert.equal(binary.at(-1),Math.fround(payload.at(-1)!/255*3));});
test('malformed base64 characters, lengths and padding fail closed',()=>{const recipe={kind:'quantized-lattice' as const,version:3 as const,vertexCount:1,bits:8,minimumWords:[0,0,0],maximumWords:[0,0,0],codes:{codec:'raw',parameters:{version:1},sourceLength:3,data:''}};for(const data of ['AAA','A===','AA=A','====','AAA!','AA A','AA\nA'])assert.throws(()=>replayQuantizedPositions({...recipe,codes:{...recipe.codes,data}}),data);});
