import type {NativeArray,NormalizedAsset} from '../src/asset-normalize-v3.ts';
export function planarGridFixture(n=2,hole=false):NormalizedAsset{
 const accessors:any[]=[],descriptors:any[]=[],add=(array:NativeArray,type:string,componentType=5126,normalized=false)=>{const id=accessors.length,count=array.length/(type==='SCALAR'?1:Number(type.at(-1)));accessors.push({sourceIndex:id,type,componentType,normalized,count,array});descriptors.push({type,componentType,count,...normalized?{normalized:true}:{}});return id;};
 const positions:number[]=[],uv:number[]=[],normals:number[]=[],tangents:number[]=[],colors:number[]=[],joints:number[]=[],weights:number[]=[],morph:number[]=[],indices:number[]=[];
 for(let y=0;y<=n;y++)for(let x=0;x<=n;x++){positions.push(x,y,0);uv.push(x/8,y/8);normals.push(0,0,1);tangents.push(1,0,0,1);colors.push(x*4,y*4,64,255);joints.push(0,0,0,0);weights.push(1,0,0,0);morph.push(x/8,y/4,(x+y)/8);}
 for(let y=0;y<n;y++)for(let x=0;x<n;x++){if(hole&&x===1&&y===1)continue;const a=y*(n+1)+x,b=a+1,c=a+n+1,d=c+1;indices.push(a,b,d,a,d,c);}
 const p:any={attributes:{POSITION:add(Float32Array.from(positions),'VEC3'),NORMAL:add(Float32Array.from(normals),'VEC3'),TANGENT:add(Float32Array.from(tangents),'VEC4'),TEXCOORD_0:add(Float32Array.from(uv),'VEC2'),COLOR_0:add(Uint8Array.from(colors),'VEC4',5121,true),JOINTS_0:add(Uint8Array.from(joints),'VEC4',5121),WEIGHTS_0:add(Float32Array.from(weights),'VEC4')},targets:[{POSITION:add(Float32Array.from(morph),'VEC3'),NORMAL:add(new Float32Array(positions.length),'VEC3')}],indices:add(Uint16Array.from(indices),'SCALAR',5123),material:0};
 const json:any={asset:{version:'2.0'},accessors:descriptors,meshes:[{primitives:[p],weights:[0]}],nodes:[{mesh:0,skin:0},{}],skins:[{joints:[1]}],materials:[{doubleSided:true}],scenes:[{nodes:[0,1]}]};
 return{format:'KEEL-NATIVE-SCENE',version:2,json,sourceJson:structuredClone(json),accessors,images:[],source:{entry:'grid.glb',container:'glb',files:[]},validation:{accessorCount:accessors.length,sourceAccessorCount:accessors.length,decodedBytes:accessors.reduce((n,a)=>n+a.array.byteLength,0),dracoPrimitives:0,meshPrimitives:1,imageBytes:0,preservedSourceIndices:true,decodedReference:'source-accessor-values',warnings:[]},runtime:{dependencies:[],dracoRequiredForReplay:false,decoderCostIncluded:false,decoderNote:''}};
}
