import test from'node:test';import assert from'node:assert/strict';
import{encodeSpriteFrames}from'../src/sprite-frame-codec.ts';import{createRasterAsset}from'../src/raster-asset.ts';import{importStyledAsset,styledAssetJson,makeStyledAssetArchive}from'../src/styled-asset.ts';import{packAsset,unpackAsset}from'../src/asset-binary-v3.ts';import{createStyledAssetPlayer}from'../src/styled-asset-player.ts';
import{createRasterCanvasPlayer,createRasterThreePlayer}from'../src/raster-player.ts';
async function fixture(){const encoded=encodeSpriteFrames({width:1,height:1,frames:[new Uint8Array([255,0,0,255]),new Uint8Array([0,255,0,128])],paletteSize:8,kind:'pixel',screen:'bayer4'});return createRasterAsset({recipe:encoded.recipe,name:'Sprite',animation:{name:'clip',sourceClip:0,start:0,duration:1,frameCount:2,fps:2,directions:1,order:'direction-major'},camera:{azimuth:0,elevation:0},renderer:'keel-import-cpu-orthographic-base-color-v1',attribution:{copyright:'test'}});}
test('v5 binary/readable assets retain sampled alpha/frames without source model data',async()=>{const a=await fixture(),b=await fixture();assert.deepEqual(a,b);const r=await importStyledAsset(a),q=await importStyledAsset(new TextEncoder().encode(styledAssetJson(a)));assert.ok('raster'in r&&'raster'in q);assert.deepEqual(r.raster.frames,q.raster.frames);assert.deepEqual(r.animation,{mode:'baked-frames',clips:1,skins:0});assert.equal(r.envelope.native.byteLength,0);assert.equal(r.envelope.native.data,undefined);assert.equal(r.nativeScene.json.animations,undefined);assert.equal(r.raster.frames[1]![3],128);const archive=makeStyledAssetArchive(a,{runtime:new TextEncoder().encode('export const valid=1;'),licenses:['LICENSE-KEEL.txt','LICENSE-fflate.txt','LICENSE-Draco-Apache-2.0.txt','LICENSE-meshoptimizer.txt'].map(name=>({name,data:'Test fixture license'}))});assert.ok(archive.length>a.length);});
test('contradictory clips and unsupported payload claims reject before playback',async()=>{const a=await fixture();for(const change of[(e:any)=>e.raster.animation.sourceClip=1e25,(e:any)=>e.raster.animation.duration=0,(e:any)=>e.raster.animation.fps=999,(e:any)=>e.raster.animation.frameCount=100,(e:any)=>e.native.data=new Uint8Array([1]),(e:any)=>e.raster.recipe.frameCount=100000000,(e:any)=>e.style.kind='original']){const e=unpackAsset(a);change(e);await assert.rejects(importStyledAsset(packAsset(e)));}});
test('Canvas playback uses real decoded frames and never changes disposed state',async()=>{const asset=await importStyledAsset(await fixture());let current:Uint8Array=new Uint8Array();const canvas:any={style:{},getContext:()=>({createImageData:(w:number,h:number)=>({data:new Uint8Array(w*h*4)}),putImageData:(x:any)=>{current=new Uint8Array(x.data);}})};const player=createRasterCanvasPlayer({canvas,asset});assert.equal(canvas.width,1);assert.equal(current[0],255);player.seek(.5);assert.equal(current[1],255);player.seek(1);assert.equal(current[0],255);player.render({delta:.5});assert.equal(current[1],255);player.dispose();assert.throws(()=>player.seek(0));assert.equal(player.time,1.5);});
function mockThree(){class Vec{values:number[]=[];set(...v:number[]){this.values=v;}}class Texture{image:any;repeat=new Vec();offset=new Vec();disposed=0;constructor(data:any,width:number,height:number){this.image={data,width,height};}dispose(){this.disposed++;}}class Material{disposed=0;constructor(input:any){Object.assign(this,input);}dispose(){this.disposed++;}}class Sprite{scale=new Vec();material:any;constructor(material:any){this.material=material;}}class Scene{children:any[]=[];add(x:any){this.children.push(x);}remove(x:any){this.children=this.children.filter(y=>y!==x);}}return{REVISION:'180',DataTexture:Texture,SpriteMaterial:Material,Sprite,Scene,Box3:class{setFromObject(){return{};}},RGBAFormat:1,NearestFilter:2,SRGBColorSpace:3};}
test('Three sprite actions stop, pause, restart, bound time and dispose idempotently',async()=>{const asset=await importStyledAsset(await fixture()),player=createRasterThreePlayer({THREE:mockThree(),renderer:{render(){}},asset});const red=player.texture.image.data;player.mixer.update(.5);assert.notDeepEqual(player.texture.image.data,red);const action=player.play();action.stop();player.mixer.update(.5);assert.deepEqual(player.texture.image.data,red);action.play();player.mixer.update(.5);assert.notDeepEqual(player.texture.image.data,red);player.mixer.stopAllAction();player.mixer.update(.5);assert.deepEqual(player.texture.image.data,red);action.play();action.paused=true;player.mixer.update(.5);assert.deepEqual(player.texture.image.data,red);action.paused=false;player.seek(1e308);assert.throws(()=>player.mixer.update(1e308));assert.equal(player.mixer.time,1e308);player.dispose();player.dispose();assert.equal(player.texture.disposed,1);assert.throws(()=>player.seek(0));assert.equal(player.mixer.time,1e308);});

test('an outdated host cannot silently play only the first raster frame',async()=>{const asset:any=await importStyledAsset(await fixture());delete asset.raster;await assert.rejects(createStyledAssetPlayer({THREE:mockThree(),renderer:{render(){}},GLTFLoader:class{},asset}),/frames are missing/);});
