import test from 'node:test';import assert from 'node:assert/strict';
import type {NormalizedAsset,NativeArray} from '../src/asset-normalize-v3.ts';
import {optimizeRenderEquivalent} from '../src/optimization/render-equivalent.ts';
function fixture():NormalizedAsset{
 const accessors:any[]=[],descriptors:any[]=[];const add=(array:NativeArray,type:string,componentType=5126)=>{const id=accessors.length,count=array.length/(type==='SCALAR'?1:Number(type.at(-1)));accessors.push({sourceIndex:id,type,componentType,count,normalized:false,array});descriptors.push({type,componentType,count});return id;};
 const p={attributes:{POSITION:add(new Float32Array([0,0,0,1,0,0,1,1,0,0,0,0,1,1,0,0,1,0]),'VEC3'),NORMAL:add(new Float32Array([0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1]),'VEC3'),TEXCOORD_0:add(new Float32Array([0,0,1,0,1,1,0,0,1,1,0,1]),'VEC2'),JOINTS_0:add(new Uint8Array(24),'VEC4',5121),WEIGHTS_0:add(new Float32Array([1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0]),'VEC4')},targets:[{POSITION:add(new Float32Array(18).fill(.125),'VEC3')}]};
 const json:any={asset:{version:'2.0'},accessors:descriptors,meshes:[{primitives:[p]}],nodes:[{mesh:0,skin:0},{}],skins:[{joints:[1]}],scenes:[{nodes:[0]}],materials:[{alphaMode:'BLEND'}]};
 return{format:'KEEL-NATIVE-SCENE',version:2,json,sourceJson:structuredClone(json),accessors,images:[],source:{entry:'fixture.glb',container:'glb',files:[]},validation:{accessorCount:accessors.length,sourceAccessorCount:accessors.length,decodedBytes:accessors.reduce((n,a)=>n+a.array.byteLength,0),dracoPrimitives:0,meshPrimitives:1,imageBytes:0,preservedSourceIndices:true,decodedReference:'source-accessor-values',warnings:[]},runtime:{dependencies:[],dracoRequiredForReplay:false,decoderCostIncluded:false,decoderNote:''}};
}
function equalCorners(a:NormalizedAsset,b:NormalizedAsset){for(let mi=0;mi<a.json.meshes.length;mi++)for(let pi=0;pi<a.json.meshes[mi].primitives.length;pi++){
 const x=a.json.meshes[mi].primitives[pi],y=b.json.meshes[mi].primitives[pi],ix=x.indices===undefined?Uint32Array.from({length:a.accessors[x.attributes.POSITION]!.count},(_,i)=>i):a.accessors[x.indices]!.array,iy=y.indices===undefined?Uint32Array.from(ix,(_,i)=>i):b.accessors[y.indices]!.array;assert.equal(ix.length,iy.length);
 for(let g=0;g<1+(x.targets?.length??0);g++){const xx=g===0?x.attributes:x.targets[g-1],yy=g===0?y.attributes:y.targets[g-1];for(const k of Object.keys(xx)){const aa=a.accessors[xx[k]]!,bb=b.accessors[yy[k]]!,stride=aa.array.byteLength/aa.count,ab=new Uint8Array(aa.array.buffer,aa.array.byteOffset,aa.array.byteLength),ba=new Uint8Array(bb.array.buffer,bb.array.byteOffset,bb.array.byteLength);for(let c=0;c<ix.length;c++)assert.deepEqual(ba.slice(iy[c]!*stride,(iy[c]!+1)*stride),ab.slice(ix[c]!*stride,(ix[c]!+1)*stride));}}}}
test('complete vertex records weld with ordered corners, morphs and rig preserved',()=>{const source=fixture(),copy=structuredClone(source),out=optimizeRenderEquivalent(source);assert.equal(out.report.outputVertices,4);assert.equal(out.report.triangles,2);assert.equal(out.report.metrics[0]!.cornerRecordsChecked,6);equalCorners(source,out.normalized);assert.deepEqual(source,copy);for(const k of ['nodes','skins','materials','scenes'])assert.deepEqual(out.normalized.json[k],source.json[k]);});
test('every stream and morph seam prevents merging, including signed zero',()=>{for(const group of ['attributes','target'])for(const key of Object.keys(group==='attributes'?fixture().json.meshes[0].primitives[0].attributes:fixture().json.meshes[0].primitives[0].targets[0])){const source=fixture(),p=source.json.meshes[0].primitives[0],id=group==='attributes'?p.attributes[key]:p.targets[0][key],a=source.accessors[id]!,width=a.array.length/a.count;if(a.array instanceof Float32Array)a.array[width*3]=Object.is(a.array[0],0)?-0:a.array[0]!+1;else a.array[width*3]=1;const out=optimizeRenderEquivalent(source);assert.equal(out.report.outputVertices,5,key);equalCorners(source,out.normalized);}});
test('shared animation and primitive accessors keep their original records',()=>{const source=fixture();source.json.animations=[{samplers:[{input:1,output:0}],channels:[]}];source.json.meshes[0].primitives.push({...structuredClone(source.json.meshes[0].primitives[0]),mode:0});const out=optimizeRenderEquivalent(source);assert.deepEqual(out.normalized.accessors[0],source.accessors[0]);assert.deepEqual(out.normalized.json.animations,source.json.animations);assert.notEqual(out.normalized.json.meshes[0].primitives[0].attributes.POSITION,0);equalCorners(source,out.normalized);});
test('opaque extras/extensions and implicit normal-map tangents are retained',()=>{for(const kind of ['root','asset','primitive','extension','tangent']){const s=fixture();if(kind==='root')s.json.extras={vertexIds:[3]};if(kind==='asset')s.json.asset.extras={vertexIds:[3]};if(kind==='primitive')s.json.meshes[0].primitives[0].extras={vertexIds:[3]};if(kind==='extension')s.json.extensionsUsed=['OTHER'];if(kind==='tangent'){s.json.meshes[0].primitives[0].material=0;s.json.materials[0].normalTexture={index:0};}const out=optimizeRenderEquivalent(s);assert.equal(out.report.changedPrimitives,0,kind);assert.deepEqual(out.normalized.json,s.json);}});
test('inert attribution metadata is retained',()=>{const s=fixture();s.json.asset.extras={author:'Author',license:'CC0',source:'https://example.org/model',title:'Title',copyright:'Author'};const out=optimizeRenderEquivalent(s);assert.equal(out.report.changedPrimitives,1);assert.deepEqual(out.normalized.json.asset,s.json.asset);});
test('unreferenced records stay intact to preserve bounds and sorting',()=>{const s=fixture(),p=s.json.meshes[0].primitives[0],id=s.accessors.length;s.accessors.push({sourceIndex:id,type:'SCALAR',componentType:5121,normalized:false,count:3,array:new Uint8Array([0,1,2])});s.json.accessors.push({type:'SCALAR',componentType:5121,count:3});p.indices=id;const out=optimizeRenderEquivalent(s);assert.equal(out.report.changedPrimitives,0);assert.match(out.report.metrics[0]!.reason,/bounds/);assert.deepEqual(out.normalized.json,s.json);});
test('deterministic outputs and invalid indices retain the original',()=>{const s=fixture();assert.deepEqual(optimizeRenderEquivalent(s),optimizeRenderEquivalent(s));const id=s.accessors.length;s.accessors.push({sourceIndex:id,type:'SCALAR',componentType:5121,normalized:false,count:3,array:new Uint8Array([0,1,99])});s.json.meshes[0].primitives[0].indices=id;const out=optimizeRenderEquivalent(s);assert.equal(out.report.changedPrimitives,0);assert.match(out.report.metrics[0]!.reason,/indices/);});
