import test from'node:test';import assert from'node:assert/strict';
import{writeNativeGlb}from'../src/asset-native-base-v3.ts';import{normalizeAsset}from'../src/asset-normalize-v3.ts';import{renderSpriteFrames}from'../src/sprite-raster.ts';import{encodePng}from'../src/png.ts';
const options={resolution:32 as const,clipIndex:null,fps:8,directions:1 as const,azimuth:0,elevation:0,shading:'unlit' as const};
async function fixture(material:any={},changes?:(j:any,a:any[])=>void){const arrays:any[]=[new Float32Array([-1,-1,0,1,-1,0,1,1,0,-1,1,0]),new Uint16Array([0,1,2,0,2,3]),new Float32Array([0,1,1,1,1,0,0,0])];const json:any={asset:{version:'2.0'},accessors:[{componentType:5126,type:'VEC3',count:4,min:[-1,-1,0],max:[1,1,0]},{componentType:5123,type:'SCALAR',count:6},{componentType:5126,type:'VEC2',count:4}],images:[{}],textures:[{source:0,sampler:0}],samplers:[{magFilter:9728,minFilter:9728,wrapS:33071,wrapT:33071}],materials:[material],meshes:[{primitives:[{attributes:{POSITION:0,TEXCOORD_0:2},indices:1,material:0}]}],nodes:[{mesh:0}],scenes:[{nodes:[0]}],scene:0};changes?.(json,arrays);const data=writeNativeGlb(json,arrays,[{mimeType:'image/png',data:encodePng({width:2,height:1,data:new Uint8Array([255,0,0,255,0,255,0,255])})}]);return normalizeAsset({entry:'model.glb',files:[{name:'model.glb',data}]});}
test('transparent raster alpha and shared triangle edge blend exactly once',async()=>{const a=await fixture({alphaMode:'BLEND',doubleSided:true,pbrMetallicRoughness:{baseColorFactor:[1,0,0,.5]}}),r=renderSpriteFrames(a,options),frame=r.frames[0]!;assert.ok(frame.some((v,i)=>i%4===3&&v===128));assert.ok(frame.every((v,i)=>i%4!==3||v===0||v===128));for(let y=12;y<20;y++)for(let x=12;x<20;x++)assert.equal(frame[(y*32+x)*4+3],128);assert.equal(frame[3],0);assert.deepEqual(renderSpriteFrames(a,options).frames,r.frames);});
test('mask cutoff, culling and opaque alpha follow source material semantics',async()=>{const masked=await fixture({alphaMode:'MASK',alphaCutoff:.5,pbrMetallicRoughness:{baseColorFactor:[1,1,1,.25]}});assert.ok(renderSpriteFrames(masked,options).frames[0]!.every(v=>v===0));const opaque=await fixture({pbrMetallicRoughness:{baseColorFactor:[1,1,1,0]}});assert.ok(renderSpriteFrames(opaque,options).frames[0]!.some((v,i)=>i%4===3&&v===255));const back=await fixture({},(_j,a)=>{a[1]=new Uint16Array([2,1,0,3,2,0]);});assert.ok(renderSpriteFrames(back,options).frames[0]!.every(v=>v===0));});
test('real texture UV transform and selected UV set change stored pixels',async()=>{const a=await fixture({pbrMetallicRoughness:{baseColorTexture:{index:0}}}),b=await fixture({pbrMetallicRoughness:{baseColorTexture:{index:0,extensions:{KHR_texture_transform:{offset:[.5,0]}}}}},j=>{j.extensionsUsed=['KHR_texture_transform'];});const before=renderSpriteFrames(a,options).frames[0]!,after=renderSpriteFrames(b,options).frames[0]!;assert.ok(before.some((v,i)=>i%4===0&&v===255));assert.ok(after.every((v,i)=>i%4!==0||v===0));assert.ok(after.some((v,i)=>i%4===1&&v===255));});
test('TRS and morph sampling produce fixed-resolution moving frames with stable framing',async()=>{const a=await fixture({},(j,v)=>{v.push(new Float32Array([0,1]),new Float32Array([0,0,0,1,0,0]),new Float32Array([0,0,0,.4,0,0,.4,0,0,0,0,0]),new Float32Array([0,1]));j.accessors.push({componentType:5126,type:'SCALAR',count:2},{componentType:5126,type:'VEC3',count:2},{componentType:5126,type:'VEC3',count:4},{componentType:5126,type:'SCALAR',count:2});j.meshes[0].weights=[0];j.meshes[0].primitives[0].targets=[{POSITION:5}];j.animations=[{name:'move',channels:[{sampler:0,target:{node:0,path:'translation'}},{sampler:1,target:{node:0,path:'weights'}}],samplers:[{input:3,output:4},{input:3,output:6}]}];});const r=renderSpriteFrames(a,{...options,clipIndex:0,fps:4});assert.equal(r.frames.length,4);assert.equal(r.animation.duration,1);assert.ok(r.frames.every(f=>f.length===32*32*4));assert.notDeepEqual(r.frames[0],r.frames[3]);assert.deepEqual(r.frames,renderSpriteFrames(a,{...options,clipIndex:0,fps:4}).frames);});
test('inactive mesh geometry is not baked, and invalid budgets fail explicitly',async()=>{const a=await fixture({},j=>{j.meshes.push({primitives:[{attributes:{POSITION:0},mode:1}]});}),r=renderSpriteFrames(a,options);assert.ok(r.frames[0]!.some(v=>v));for(const bad of[{resolution:0},{fps:NaN},{directions:3},{clipIndex:99},{elevation:2}])assert.throws(()=>renderSpriteFrames(a,{...options,...bad} as any));});
test('mirrored single-sided instances remain visible and instanced index work is bounded',async()=>{const a=await fixture({pbrMetallicRoughness:{baseColorFactor:[1,0,0,1]}}),b=await fixture({pbrMetallicRoughness:{baseColorFactor:[1,0,0,1]}},j=>{j.nodes[0].scale=[-1,1,1];});assert.deepEqual(renderSpriteFrames(a,options).frames,renderSpriteFrames(b,options).frames);const many=structuredClone(a);many.json.nodes=Array.from({length:1000},()=>({mesh:0}));many.json.scenes=[{nodes:Array.from({length:1000},(_,i)=>i)}];many.accessors[1]!.array=Uint32Array.from({length:750000},(_,i)=>i%3);many.accessors[1]!.count=750000;many.accessors[1]!.componentType=5125;assert.throws(()=>renderSpriteFrames(many,options),/triangle budget/);});
test('reflected scale sampling follows the last duplicate initial key',async()=>{const a=await fixture({},(j,v)=>{v.push(new Float32Array([0,0,1]),new Float32Array([1,1,1,-1,1,1,-1,1,1]));j.accessors.push({componentType:5126,type:'SCALAR',count:3},{componentType:5126,type:'VEC3',count:3});j.animations=[{samplers:[{input:3,output:4}],channels:[{sampler:0,target:{node:0,path:'scale'}}]}];});const r=renderSpriteFrames(a,{...options,clipIndex:0,fps:2});assert.ok(r.frames.every(f=>f.some((v,i)=>i%4===3&&v===255)));});
