import test from 'node:test';
import assert from 'node:assert/strict';
import {encodeTopologyAttribute,replayTopologyAttribute,TOPOLOGY_PREDICTOR_POLICY} from '../src/optimization/topology-predictor.ts';
import type {TopologyAttributeInput,TriangleIndices} from '../src/optimization/topology-predictor.ts';
import {packAsset,unpackAsset} from '../src/asset-binary-v3.ts';
const bytes=(a:ArrayBufferView)=>new Uint8Array(a.buffer,a.byteOffset,a.byteLength);
function grid(n=48){const indices:number[]=[];for(let y=0;y<n-1;y++)for(let x=0;x<n-1;x++){const a=y*n+x,b=a+1,c=a+n,d=c+1;indices.push(a,b,c,b,d,c);}const array=new Uint32Array(n*n*3);let state=19;const next=()=>state=(Math.imul(state,1664525)+1013904223)>>>0;const u=Array.from({length:n*3},()=>next()&0xffff),v=Array.from({length:n*3},()=>next()&0xffff);for(let y=0;y<n;y++)for(let x=0;x<n;x++)for(let c=0;c<3;c++)array[(y*n+x)*3+c]=(x&&y?array[(y*n+x-1)*3+c]!+array[((y-1)*n+x)*3+c]!-array[((y-1)*n+x-1)*3+c]!:u[x*3+c]!+v[y*3+c]!)+(next()%23===0?next()&255:0);return{array,indices:Uint16Array.from(indices),type:'VEC3',componentType:5125,normalized:false,count:n*n};}
function exact(input:TopologyAttributeInput){const a=encodeTopologyAttribute(input),b=encodeTopologyAttribute(input);assert.deepEqual(packAsset(a.recipe),packAsset(b.recipe));assert.ok(a.metrics.recipeBytes<=a.metrics.residualRecipeBytes);assert.ok(a.metrics.fullCandidates<=TOPOLOGY_PREDICTOR_POLICY.fullCandidates);assert.deepEqual(bytes(replayTopologyAttribute(unpackAsset(packAsset(a.recipe)) as typeof a.recipe,input.indices)),bytes(input.array));return a;}
test('topology parallelograms win on source-derived curved grids with no parent bytes',()=>{const input=grid(),result=exact(input);assert.equal(result.recipe.kind,'topology');assert.ok(result.metrics.parallelogramVertices>2000);assert.equal(result.metrics.parentTableBytes,0);assert.ok(result.metrics.recipeBytes<result.metrics.residualRecipeBytes);});
test('all Float32 words survive, including signaling NaNs, payloads, signed zeros and infinities',()=>{const source=grid(),array=new Float32Array(source.array.length);for(let i=0;i<array.length;i++)array[i]=source.array[i]!;const words=new Uint32Array(array.buffer),special=[0,0x80000000,0x7f800000,0xff800000,0x7f800001,0x7fa12345,0xffc54321,1,0x80000001,0x7fffffff];for(let i=0;i<special.length;i++)words[i*37]=special[i]!;assert.equal(exact({...source,array,componentType:5126}).recipe.kind,'topology');});
test('affine integer domain is optional, word-verified, and reproducible',()=>{const source=grid(),hint={kind:'float-affine' as const,width:3,bits:18,minimum:[-5,0.125,10],scale:Math.fround(0.0037)},array=new Float32Array(source.array.length);for(let i=0;i<array.length;i++)array[i]=Math.fround(Math.fround(source.array[i]!*hint.scale)+hint.minimum[i%3]!);const input={...source,array,componentType:5126},result=encodeTopologyAttribute(input,hint);assert.equal(result.metrics.fullCandidates,2);assert.equal(result.metrics.selected,'topology-affine');assert.deepEqual(bytes(replayTopologyAttribute(result.recipe,input.indices)),bytes(array));assert.deepEqual(packAsset(result.recipe),packAsset(encodeTopologyAttribute(input,hint).recipe));new Uint32Array(array.buffer)[7]=0x7fa23456;const rejected=encodeTopologyAttribute(input,hint);assert.equal(rejected.metrics.fullCandidates,1);assert.deepEqual(bytes(replayTopologyAttribute(rejected.recipe,input.indices)),bytes(array));});
test('skinned and morph streams replay every original component independently',()=>{const source=grid(20),count=source.count,streams:TopologyAttributeInput[]=[];const joints=new Uint8Array(count*4),weights=new Float32Array(count*4),morph=new Int16Array(count*3);for(let v=0;v<count;v++){for(let k=0;k<4;k++){joints[v*4+k]=(v+k)%64;weights[v*4+k]=Math.fround(((v+k)%4)/6);}for(let k=0;k<3;k++)morph[v*3+k]=source.array[v*3+k]!;}streams.push({...source,array:joints,type:'VEC4',componentType:5121}, {...source,array:weights,type:'VEC4',componentType:5126},{...source,array:morph,componentType:5122,normalized:true});for(const stream of streams)exact(stream);});
test('degenerate, disconnected, non-manifold, repeated, and unreferenced vertices are retained',()=>{const array=Uint32Array.from([0,0xffffffff,1,0x80000000,7,7,9,0x7fffffff,4,0,8,2]);for(const C of[Uint8Array,Uint16Array,Uint32Array])exact({array,indices:new C([0,0,0,0,1,2,0,1,3,0,1,4,2,1,0,8,9,10]),type:'SCALAR',componentType:5125,normalized:false,count:array.length});exact({array:new Int8Array(0),indices:new Uint8Array(0),type:'VEC4',componentType:5120,normalized:true,count:0});});
test('typed subarrays use only declared bytes and baseline is used for tiny incompressible arrays',()=>{const storage=Uint32Array.from([123,1,0xffffffff,0x87654321,5]),array=storage.subarray(1,4),input={array,indices:new Uint8Array([0,1,2]),type:'SCALAR',componentType:5125,normalized:false,count:3},result=exact(input);assert.equal(result.recipe.kind,'residual');});
test('malformed descriptor, topology, and dependency mismatch fail before prediction',()=>{const input=grid();assert.throws(()=>encodeTopologyAttribute({...input,count:input.count+1}),/array differs/);assert.throws(()=>encodeTopologyAttribute({...input,type:'VEC5'}),/descriptor/);assert.throws(()=>encodeTopologyAttribute({...input,indices:new Uint16Array([0,1])}),/triangle/);assert.throws(()=>encodeTopologyAttribute({...input,indices:new Uint32Array([0,1,input.count])}),/outside/);const{recipe}=encodeTopologyAttribute(input);assert.equal(recipe.kind,'topology');assert.throws(()=>replayTopologyAttribute(recipe),/missing topology/);const other=input.indices.slice();other[0]=3;assert.throws(()=>replayTopologyAttribute(recipe,other),/dependency differs/);if(recipe.kind==='topology'){assert.throws(()=>replayTopologyAttribute({...recipe,wordBytes:3},input.indices),/extent/);assert.throws(()=>replayTopologyAttribute({...recipe,payload:{...recipe.payload,sourceLength:4}},input.indices),/extent/);assert.throws(()=>replayTopologyAttribute({...recipe,payload:{...recipe.payload,data:recipe.payload.data.subarray(0,4)}},input.indices));assert.throws(()=>replayTopologyAttribute({...recipe,domain:{kind:'affine',bits:16,minimumWords:[0,0,0],scaleWord:0}},input.indices),/Float32/);}});

test('oversized topology work falls back without emitting a new decoder dependency',()=>{const input={array:new Uint8Array([1]),indices:new Uint8Array((TOPOLOGY_PREDICTOR_POLICY.maxTriangles+1)*3),type:'SCALAR',componentType:5121,normalized:false,count:1},result=encodeTopologyAttribute(input);assert.equal(result.recipe.kind,'residual');assert.equal(result.metrics.fullCandidates,0);assert.match(result.metrics.skipReason!,/budget/);assert.deepEqual(replayTopologyAttribute(result.recipe),input.array);});
