import assert from 'node:assert/strict';
import {test} from 'node:test';
import {optimizeUnusedTangents,optimizeUnusedRenderAttributes} from '../src/optimization/exact-geometry-experiment.ts';
const a=(sourceIndex:number,type:string,count:number,width:number)=>({sourceIndex,type,count,componentType:5126,normalized:false,array:Float32Array.from({length:count*width},(_,i)=>i/7)});
function fixture():any{const accessors=[a(0,'VEC3',3,3),a(1,'VEC4',3,4),a(2,'VEC2',3,2),a(3,'MAT4',1,16),a(4,'SCALAR',2,1),a(5,'VEC3',2,3),a(6,'VEC3',3,3),a(7,'VEC2',3,2)];const json={asset:{version:'2.0'},accessors:accessors.map(({array,sourceIndex,...d})=>d),meshes:[{primitives:[{attributes:{POSITION:0,TANGENT:1,TEXCOORD_0:2,TEXCOORD_1:7},targets:[{POSITION:6}],material:0}]}],materials:[{pbrMetallicRoughness:{baseColorTexture:{index:0}}}],skins:[{inverseBindMatrices:3,joints:[0]}],nodes:[{mesh:0,skin:0}],animations:[{samplers:[{input:4,output:5}],channels:[{sampler:0,target:{node:0,path:'translation'}}]}]};return{format:'KEEL-NATIVE-SCENE',version:2,json,sourceJson:structuredClone(json),accessors,images:[],source:{entry:'fixture.gltf'},runtime:{},validation:{accessorCount:accessors.length,decodedBytes:0}};}
const stable=(a:any)=>JSON.stringify(a);
test('removes unused tangent and UV, remaps skin animation and morph references, preserves source audit',()=>{const source=fixture(),before=structuredClone(source),r=optimizeUnusedRenderAttributes(source);assert.equal(r.report.removedAccessors,2);assert.equal(r.report.changedPrimitives,1);assert.deepEqual(r.accessorRemap,[0,-1,1,2,3,4,5,-1]);assert.deepEqual(r.normalized.json.meshes[0].primitives[0].attributes,{POSITION:0,TEXCOORD_0:1});assert.equal(r.normalized.json.skins[0].inverseBindMatrices,2);assert.deepEqual(r.normalized.json.animations[0].samplers[0],{input:3,output:4});assert.equal(r.normalized.json.meshes[0].primitives[0].targets[0].POSITION,5);assert.equal(stable(source),stable(before));assert.equal(r.normalized.sourceJson,source.sourceJson);for(let i=0;i<source.accessors.length;i++)if(r.accessorRemap[i]!>=0)assert.equal(r.normalized.accessors[r.accessorRemap[i]!],source.accessors[i]);});
test('normal-mapped primitive retains tangent; sharing with it retains accessor',()=>{const source=fixture(),p=structuredClone(source.json.meshes[0].primitives[0]);source.json.materials.push({normalTexture:{index:0}});p.material=1;source.json.meshes[0].primitives.push(p);const r=optimizeUnusedTangents(source);assert.equal(r.report.changedPrimitives,1);assert.equal(r.report.removedAccessors,0);assert.equal(r.normalized.json.meshes[0].primitives[1].attributes.TANGENT,1);});
test('tangent morph and opaque metadata or shader hooks are skipped',()=>{for(const mutate of [(s:any)=>s.json.meshes[0].primitives[0].targets[0].TANGENT=1,(s:any)=>s.json.materials[0].extensions={KHR_materials_anisotropy:{anisotropyStrength:1}},(s:any)=>s.json.materials[0].extensions={KHR_materials_clearcoat:{clearcoatNormalTexture:{index:0}}},(s:any)=>s.json.extras={shader:'custom'},(s:any)=>s.json.meshes[0].primitives[0].extras={shader:'custom'},(s:any)=>s.json.meshes[0].primitives[0].attributes._CUSTOM=2,(s:any)=>s.json.extensionsUsed=['UNKNOWN']]){const source=fixture();mutate(source);assert.equal(optimizeUnusedTangents(source).report.changedPrimitives,0);}});
test('all five core texture roles retain the referenced UV set, including default UV zero',()=>{for(const [k,nested] of [['baseColorTexture',true],['metallicRoughnessTexture',true],['normalTexture',false],['occlusionTexture',false],['emissiveTexture',false]] as Array<[string,boolean]>){const source=fixture();source.json.materials[0]=nested?{pbrMetallicRoughness:{[k]:{index:0,texCoord:1}}}:{[k]:{index:0,texCoord:1}};const r=optimizeUnusedRenderAttributes(source);assert.ok(r.normalized.json.meshes[0].primitives[0].attributes.TEXCOORD_1!==undefined);assert.equal(r.normalized.json.meshes[0].primitives[0].attributes.TEXCOORD_0,undefined);}});
test('permitted string-only attribution stays exact, unknown attribution blocks compaction',()=>{const source=fixture();source.json.asset.extras={author:'Artist',license:'CC-BY',source:'https://example.test'};assert.equal(optimizeUnusedTangents(source).report.changedPrimitives,1);source.json.asset.extras.shader='custom';assert.equal(optimizeUnusedTangents(source).report.changedPrimitives,0);});
