/*! Octahedral coordinate convention derived from Google Draco 1.5.7.
 * Copyright 2016 The Draco Authors. SPDX-License-Identifier: Apache-2.0
 * https://www.apache.org/licenses/LICENSE-2.0 */
/** Source-grounded cross-attribute experiment. Geometric area normals predict
 * octahedral codes; exact residuals preserve every decoded normal word.
 * Reference: https://google.github.io/draco/spec/#normal-prediction-decoder */
import{decodeAttribute}from'../asset-normal-codec-v3.ts';
import type{OctHint}from'./draco-transforms.ts';
const MAX=1048576;
export interface GeometricNormalRecipe{kind:'geometric-oct-residual';version:1;bits:number;count:number;normalized:boolean;predictor:'area';residuals:Uint8Array}
function octEncode(x:number,y:number,z:number,bits:number):number[]{const maximum=2**bits-2,center=maximum/2,sum=Math.abs(x)+Math.abs(y)+Math.abs(z);if(!Number.isFinite(sum))return[center,center];const scale=sum>1e-6?1/sum:0;let a=Math.floor((scale?x*scale:1)*center+.5),b=Math.floor(y*scale*center+.5),c=center-Math.abs(a)-Math.abs(b);if(c<0){b+=b>0?c:-c;c=0}if(z*scale<0)c=-c;let s=a>=0?b+center:b<0?Math.abs(c):maximum-Math.abs(c),t=a>=0?c+center:c<0?Math.abs(b):maximum-Math.abs(b);if((s===0&&t===0)||(s===0&&t===maximum)||(s===maximum&&t===0)){s=maximum;t=maximum}else if(s===0&&t>center)t=maximum-t;else if(s===maximum&&t<center)t=maximum-t;else if(t===maximum&&s<center)s=maximum-s;else if(t===0&&s>center)s=maximum-s;return[s,t]}
function predict(positions:Float32Array,indices:Uint8Array|Uint16Array|Uint32Array,bits:number){
 if(!(positions instanceof Float32Array)||positions.length%3||positions.length/3>MAX||positions.some(x=>!Number.isFinite(x))||!(indices instanceof Uint8Array||indices instanceof Uint16Array||indices instanceof Uint32Array)||indices.length%3||indices.length>MAX*6||!Number.isInteger(bits)||bits<2||bits>16)throw Error('Invalid geometric normal inputs');const count=positions.length/3,sums=new Float64Array(positions.length);
 for(let i=0;i<indices.length;i+=3){const a=indices[i]!,b=indices[i+1]!,c=indices[i+2]!;if(a>=count||b>=count||c>=count)throw Error('Normal topology out of range');const x=positions[b*3]!-positions[a*3]!,y=positions[b*3+1]!-positions[a*3+1]!,z=positions[b*3+2]!-positions[a*3+2]!,u=positions[c*3]!-positions[a*3]!,v=positions[c*3+1]!-positions[a*3+1]!,w=positions[c*3+2]!-positions[a*3+2]!,nx=y*w-z*v,ny=z*u-x*w,nz=x*v-y*u;for(const id of[a,b,c]){sums[id*3]!+=nx;sums[id*3+1]!+=ny;sums[id*3+2]!+=nz;}}
 const pairs=new Uint32Array(count*2);for(let i=0;i<count;i++){const a=sums[i*3]!,b=sums[i*3+1]!,c=sums[i*3+2]!,scale=Math.max(Math.abs(a),Math.abs(b),Math.abs(c));pairs.set(octEncode(scale?a/scale:0,scale?b/scale:0,scale?c/scale:0,bits),i*2);}return pairs;
}
function pack(pairs:Uint32Array,bits:number){const data=new Uint8Array(Math.ceil(pairs.length*bits/8));let bit=0;for(const v of pairs)for(let k=0;k<bits;k++,bit++)if(v&(2**k))data[bit>>>3]!|=1<<(bit&7);return data;}
export function replayGeometricNormals(recipe:GeometricNormalRecipe,positions:Float32Array,indices:Uint8Array|Uint16Array|Uint32Array):Float32Array{
 if(recipe?.kind!=='geometric-oct-residual'||recipe.version!==1||recipe.predictor!=='area'||!Number.isSafeInteger(recipe.count)||recipe.count<1||recipe.count>MAX||typeof recipe.normalized!=='boolean'||recipe.count*3!==positions.length||!(recipe.residuals instanceof Uint8Array)||recipe.residuals.length!==recipe.count*4)throw Error('Invalid geometric normal recipe');const pairs=predict(positions,indices,recipe.bits),n=pairs.length,mask=2**recipe.bits-1;
 for(let i=0;i<n;i++){const zz=recipe.residuals[i]!|(recipe.residuals[n+i]!<<8);if(zz>mask)throw Error('Normal residual exceeds its canonical domain');const delta=zz&1?-(zz+1)/2:zz/2;pairs[i]=(pairs[i]!+delta)&mask;if(pairs[i]!>=mask)throw Error('Normal residual produces an invalid oct coordinate');}
 const data=pack(pairs,recipe.bits);return decodeAttribute({version:3,componentType:5126,type:'VEC3',count:recipe.count,normalized:recipe.normalized,storage:{kind:'octahedral-f32',bits:recipe.bits,predictor:0,pairs:{codec:'raw',parameters:{version:1},sourceLength:data.length,data}}})as Float32Array;
}
export function encodeGeometricNormals(normals:Float32Array,positions:Float32Array,indices:Uint8Array|Uint16Array|Uint32Array,hint:OctHint,normalized=false){
 if(normals.length===0||normals.length/3>MAX)return null;
 if(!(normals instanceof Float32Array)||normals.length!==positions.length||hint?.kind!=='octahedral'||hint.source.length%3||hint.pairs.length!==hint.source.length/3*2)throw Error('Invalid source normal domain');const prediction=predict(positions,indices,hint.bits),count=normals.length/3,words=new Uint32Array(normals.buffer,normals.byteOffset,normals.length),sourceWords=new Uint32Array(hint.source.buffer,hint.source.byteOffset,hint.source.length),lookup=new Map<string,number>();for(let i=0;i<sourceWords.length;i+=3)lookup.set(sourceWords[i]+','+sourceWords[i+1]+','+sourceWords[i+2],i/3);
 const n=count*2,residuals=new Uint8Array(n*2),mask=2**hint.bits-1,half=2**(hint.bits-1);let zeros=0;for(let i=0;i<count;i++){const row=lookup.get(words[i*3]+','+words[i*3+1]+','+words[i*3+2]);if(row===undefined)return null;for(let lane=0;lane<2;lane++){const at=i*2+lane;let delta=(hint.pairs[row*2+lane]!-prediction[at]!)&mask;if(delta>=half)delta-=mask+1;const zz=delta<0?-2*delta-1:2*delta;residuals[at]=zz&255;residuals[n+at]=zz>>>8;if(!delta)zeros++;}}
 const recipe:GeometricNormalRecipe={kind:'geometric-oct-residual',version:1,bits:hint.bits,count,normalized,predictor:'area',residuals},decoded=replayGeometricNormals(recipe,positions,indices),actual=new Uint32Array(decoded.buffer);if(actual.some((v,i)=>v!==words[i]))return null;return{recipe,metrics:{vectors:count,zeroResiduals:zeros,residualCoordinates:n,exactWords:words.length,dependency:'source positions plus ordered triangle indices; no normal regenerated without its exact residual'}};
}
