/** Exact typed-attribute packing. Arithmetic grids are inferred, never quantized:
 * every Float32 mismatch, signed zero and NaN payload is retained as an exact patch.
 * Candidate order and bounded probes are fixed by this version. No asset-specific rules.
 */
import { encodeBuffer, decodeBuffer } from './asset-buffer-codec.ts';
export const ATTRIBUTE_CODEC_VERSION = 3;
const MAX_BYTES = 256 * 1024 * 1024, MAX_LATTICE_VALUES = 4194304;
const DENOMINATORS = [...Array.from({length:64},(_,i)=>i+1),100,1000,10000,100000,1000000,10000000,100000000,255,1023,4095,65535];
const COMPONENTS:Record<string,number>={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16};
const CTORS={5120:Int8Array,5121:Uint8Array,5122:Int16Array,5123:Uint16Array,5125:Uint32Array,5126:Float32Array};
type ComponentType=keyof typeof CTORS;
export type AttributeArray=Int8Array|Uint8Array|Int16Array|Uint16Array|Uint32Array|Float32Array;
export interface AttributeInput{array:AttributeArray;componentType:number;type:string;count:number;normalized:boolean}
export interface AttributeBuffer{codec:string;parameters:Record<string,number>;sourceLength:number;data:Uint8Array}
type Storage={kind:'buffer';buffer:AttributeBuffer}|{kind:'packed-integers';base:number;bits:number;predictor:0|1;buffer:AttributeBuffer}|{kind:'scaled-f32';denominator:number;base:number;bits:number;predictor:0|1;buffer:AttributeBuffer;exceptions?:AttributeBuffer};
export interface AttributeRecipe{version:3;componentType:ComponentType;type:string;count:number;normalized:boolean;storage:Storage}
export interface AttributeMetrics{selected:string;sourceBytes:number;recipeBytes:number;baselineBytes:number;payloadBytes:number;metadataBytes:number;exceptionCount:number;candidates:Array<{kind:string;bytes:number;denominator?:number;predictor?:number}>;costBasis:string;exact:true}
function integer(x:unknown,min:number,max:number,label:string):number{if(typeof x!=='number'||!Number.isSafeInteger(x)||x<min||x>max)throw Error('Attribute codec: invalid '+label);return x}
function shape(componentType:number,type:string,count:number){if(typeof componentType!=='number'||!Number.isSafeInteger(componentType)||typeof type!=='string'||!Object.hasOwn(COMPONENTS,type))throw Error('Attribute codec: invalid descriptor tags');const C=CTORS[componentType as ComponentType],width=COMPONENTS[type];if(!C||!width)throw Error('Attribute codec: unsupported component/type');integer(count,0,MAX_BYTES,'count');const values=count*width,length=values*C.BYTES_PER_ELEMENT;if(!Number.isSafeInteger(length)||length>MAX_BYTES)throw Error('Attribute codec: attribute exceeds limit');return{C,width,values,length};}
function canonicalBytes(array:AttributeArray,componentType:ComponentType):Uint8Array{const out=new Uint8Array(array.byteLength),view=new DataView(out.buffer);if(componentType===5120||componentType===5121){out.set(new Uint8Array(array.buffer,array.byteOffset,array.byteLength));return out}const words=componentType===5126?new Uint32Array(array.buffer,array.byteOffset,array.length):null;for(let i=0;i<array.length;i++){if(componentType===5122)view.setInt16(i*2,array[i]!,true);else if(componentType===5123)view.setUint16(i*2,array[i]!,true);else view.setUint32(i*4,words?words[i]!:array[i]!,true)}return out;}
function fromBytes(data:Uint8Array,componentType:ComponentType):AttributeArray{const C=CTORS[componentType],out=new C(data.length/C.BYTES_PER_ELEMENT) as AttributeArray,view=new DataView(data.buffer,data.byteOffset,data.byteLength);if(C.BYTES_PER_ELEMENT===1){new Uint8Array(out.buffer).set(data);return out}const words=componentType===5126?new Uint32Array(out.buffer):null;for(let i=0;i<out.length;i++){if(words)words[i]=view.getUint32(i*4,true);else out[i]=componentType===5122?view.getInt16(i*2,true):componentType===5123?view.getUint16(i*2,true):view.getUint32(i*4,true)}return out;}
function buffer(bytes:Uint8Array,hints?:{stride:number;componentBytes:number}):AttributeBuffer{const e=encodeBuffer(bytes,hints);return{codec:e.codec,parameters:e.parameters,sourceLength:e.sourceLength,data:e.data}}
function cost(recipe:AttributeRecipe){let payloadBytes=0;const metadata=JSON.stringify(recipe,(_key,value)=>{if(value instanceof Uint8Array){payloadBytes+=value.length;return{$binaryLength:value.length}}return value}),metadataBytes=new TextEncoder().encode(metadata).length;return{payloadBytes,metadataBytes,total:payloadBytes+metadataBytes};}
function bitsFor(max:number):number{return max===0?0:Math.ceil(Math.log2(max+1))}
function pack(values:ArrayLike<number>,bits:number):Uint8Array{const out=new Uint8Array(Math.ceil(values.length*bits/8));let bit=0;for(let i=0;i<values.length;i++){const v=values[i]!;let remaining=bits,offset=0;while(remaining){const lane=bit%8,take=Math.min(8-lane,remaining),mask=(1<<take)-1;out[Math.floor(bit/8)]!|=((v>>>offset)&mask)<<lane;bit+=take;offset+=take;remaining-=take}}return out;}
function unpack(data:Uint8Array,bits:number,count:number):Uint32Array{if(data.length!==Math.ceil(count*bits/8))throw Error('Attribute codec: packed extent differs');const out=new Uint32Array(count);let bit=0;for(let i=0;i<count;i++){let v=0,remaining=bits,offset=0;while(remaining){const lane=bit%8,take=Math.min(8-lane,remaining),mask=(1<<take)-1;v+=((data[Math.floor(bit/8)]!>>>lane)&mask)*2**offset;bit+=take;offset+=take;remaining-=take}out[i]=v}if(bit%8&&data.length&&(data[data.length-1]!>>>(bit%8)))throw Error('Attribute codec: nonzero padding bits');return out;}
function coded(q:ArrayLike<number>,base:number,width:number,predictor:0|1):{values:Uint32Array;bits:number}|null{let max=0;const out=new Uint32Array(q.length);for(let i=0;i<q.length;i++){const value=q[i]!-base,previous=i>=width?q[i-width]!-base:0,difference=value-previous,code=predictor?(difference<0?-2*difference-1:2*difference):value;if(!Number.isSafeInteger(code)||code<0||code>0xffffffff)return null;out[i]=code;max=Math.max(max,code)}return{values:out,bits:bitsFor(max)}}
function restoreCodes(code:Uint32Array,base:number,width:number,predictor:0|1):Float64Array{const out=new Float64Array(code.length);for(let i=0;i<code.length;i++){const v=code[i]!;out[i]=predictor?(i>=width?out[i-width]!:base)+(v%2?-(v+1)/2:v/2):base+v}return out;}
function patchBytes(indices:number[],words:Uint32Array):Uint8Array{const out:number[]=[];let previous=-1;for(const index of indices){let delta=index-previous;previous=index;while(delta>=128){out.push((delta&127)|128);delta=Math.floor(delta/128)}out.push(delta);const word=words[index]!;out.push(word&255,word>>>8&255,word>>>16&255,word>>>24)}return new Uint8Array(out);}
function applyPatches(bytes:Uint8Array,out:Uint32Array):number{let cursor=0,previous=-1,count=0;while(cursor<bytes.length){let delta=0,shift=0,b=0;do{if(cursor>=bytes.length||shift>=35)throw Error('Attribute codec: invalid patch index');b=bytes[cursor++]!;delta+=(b&127)*2**shift;shift+=7}while(b&128);if(!Number.isSafeInteger(delta)||delta<1||previous+delta>=out.length||cursor+4>bytes.length)throw Error('Attribute codec: patch out of range');previous+=delta;out[previous]=(bytes[cursor]!|bytes[cursor+1]!<<8|bytes[cursor+2]!<<16|bytes[cursor+3]!<<24)>>>0;cursor+=4;count++}return count;}
function same(a:Uint8Array,b:Uint8Array){return a.length===b.length&&a.every((v,i)=>v===b[i])}
export function encodeAttribute(input:AttributeInput):{recipe:AttributeRecipe;metrics:AttributeMetrics}{
 const{C,width,values,length}=shape(input.componentType,input.type,input.count);if(!(input.array instanceof C)||input.array.length!==values||typeof input.normalized!=='boolean')throw Error('Attribute codec: descriptor/array mismatch');
 const componentType=input.componentType as ComponentType,raw=canonicalBytes(input.array,componentType),baseRecipe={version:3 as const,componentType,type:input.type,count:input.count,normalized:input.normalized};
 let recipe:AttributeRecipe={...baseRecipe,storage:{kind:'buffer',buffer:buffer(raw,{stride:width*C.BYTES_PER_ELEMENT,componentBytes:C.BYTES_PER_ELEMENT})}},selectedCost=cost(recipe),exceptionCount=0;
 const baselineBytes=selectedCost.total,candidates:AttributeMetrics['candidates']=[{kind:'buffer',bytes:baselineBytes}];
 const consider=(storage:Storage,exceptions=0)=>{const candidate={...baseRecipe,storage},bytes=cost(candidate);candidates.push({kind:storage.kind,bytes:bytes.total,...(storage.kind==='scaled-f32'?{denominator:storage.denominator,predictor:storage.predictor}:storage.kind==='packed-integers'?{predictor:storage.predictor}:{})});if(bytes.total<selectedCost.total){recipe=candidate;selectedCost=bytes;exceptionCount=exceptions}};
 if(values&&length>=64&&values<=MAX_LATTICE_VALUES){
  if(componentType!==5126){let min=Infinity;for(const value of input.array)min=Math.min(min,value);for(const predictor of[0,1]as const){const code=coded(input.array,min,width,predictor);if(code)consider({kind:'packed-integers',base:min,bits:code.bits,predictor,buffer:buffer(pack(code.values,code.bits))})}}
  else{
   const source=input.array as Float32Array,words=new Uint32Array(source.buffer,source.byteOffset,source.length),scratch=new DataView(new ArrayBuffer(4)),samples=Math.min(values,96);
   const inferred=new Set<number>();for(let i=width;i<Math.min(values,width*33)&&inferred.size<16;i++){const delta=Math.abs(source[i]!-source[i-width]!);if(delta>0&&Number.isFinite(delta)){const reciprocal=Math.round(1/delta);if(Number.isSafeInteger(reciprocal)&&reciprocal>=1&&reciprocal<=1000000000)inferred.add(reciprocal)}}
   const denominators=[...new Set([...DENOMINATORS,...inferred])],scored:Array<{denominator:number;estimate:number}>=[];
   for(const denominator of denominators){let min=Infinity,max=-Infinity,exceptions=0;for(let s=0;s<samples;s++){const index=samples===1?0:Math.floor(s*(values-1)/(samples-1)),value=source[index]!,rounded=Math.round(value*denominator),q=Number.isFinite(rounded)&&rounded>=-2147483648&&rounded<=2147483647?(rounded||0):0;scratch.setFloat32(0,Math.fround(q/denominator),true);if(scratch.getUint32(0,true)!==words[index])exceptions++;min=Math.min(min,q);max=Math.max(max,q)}if(exceptions<=samples/8)scored.push({denominator,estimate:values*bitsFor(max-min)/8+values*exceptions/samples*5})}
   scored.sort((a,b)=>a.estimate-b.estimate||a.denominator-b.denominator);
   for(const{denominator}of scored.slice(0,3)){const q=new Int32Array(values),exceptions:number[]=[];let min=Infinity,valid=true;for(let i=0;i<values;i++){const rounded=Math.round(source[i]!*denominator),value=Number.isFinite(rounded)&&rounded>=-2147483648&&rounded<=2147483647?(rounded||0):0;q[i]=value;min=Math.min(min,value);scratch.setFloat32(0,Math.fround(value/denominator),true);if(scratch.getUint32(0,true)!==words[i]){exceptions.push(i);if(exceptions.length>Math.min(values/8,262144)){valid=false;break}}}if(!valid)continue;const patches=exceptions.length?buffer(patchBytes(exceptions,words)):undefined;for(const predictor of[0,1]as const){const code=coded(q,min,width,predictor);if(!code)continue;consider({kind:'scaled-f32',denominator,base:min,bits:code.bits,predictor,buffer:buffer(pack(code.values,code.bits)),...(patches?{exceptions:patches}:{})},exceptions.length)}}
  }
 }
 const decoded=decodeAttribute(recipe);if(!same(raw,canonicalBytes(decoded,componentType))){const actual=canonicalBytes(decoded,componentType),index=raw.findIndex((v,i)=>v!==actual[i]);throw Error('Attribute codec: internal exactness check failed at byte '+index+' for '+recipe.storage.kind+' expected '+raw[index]+' actual '+actual[index]);}
 return{recipe,metrics:{selected:recipe.storage.kind,sourceBytes:length,recipeBytes:selectedCost.total,baselineBytes,payloadBytes:selectedCost.payloadBytes,metadataBytes:selectedCost.metadataBytes,exceptionCount,candidates,costBasis:'Canonical UTF-8 recipe metadata with binary-length markers plus actual binary payload bytes; fixed shared decoder counted once by the outer package selector',exact:true}};
}
export function decodeAttribute(recipe:AttributeRecipe):AttributeArray{
 if(!recipe||recipe.version!==ATTRIBUTE_CODEC_VERSION||typeof recipe.normalized!=='boolean')throw Error('Attribute codec: unsupported recipe');const{C,width,values,length}=shape(recipe.componentType,recipe.type,recipe.count),s=recipe.storage;if(!s||typeof s!=='object')throw Error('Attribute codec: missing storage');
 const read=(b:AttributeBuffer,expected?:number)=>{if(!b||!(b.data instanceof Uint8Array)||(expected!==undefined&&b.sourceLength!==expected))throw Error('Attribute codec: buffer extent differs');integer(b.sourceLength,0,MAX_BYTES,'buffer length');return decodeBuffer(b,MAX_BYTES)};
 if(s.kind==='buffer')return fromBytes(read(s.buffer,length),recipe.componentType);
 if(s.kind!=='packed-integers'&&s.kind!=='scaled-f32')throw Error('Attribute codec: unknown storage');if(values>MAX_LATTICE_VALUES)throw Error('Attribute codec: packed value budget exceeded');integer(s.bits,0,32,'packed width');integer(s.base,-2147483648,4294967295,'integer base');integer(s.predictor,0,1,'predictor');
 const packedLength=Math.ceil(values*s.bits/8);if(packedLength>MAX_BYTES)throw Error('Attribute codec: packed payload too large');const q=restoreCodes(unpack(read(s.buffer,packedLength),s.bits,values),s.base,width,s.predictor);
 if(s.kind==='scaled-f32'){
  if(recipe.componentType!==5126)throw Error('Attribute codec: float lattice requires Float32');integer(s.denominator,1,1000000000,'denominator');const out=new Float32Array(values);for(let i=0;i<values;i++){integer(q[i],-2147483648,2147483647,'scaled integer');out[i]=Math.fround(q[i]!/s.denominator)}if(s.exceptions){if(s.exceptions.sourceLength>Math.min(MAX_BYTES,values*9))throw Error('Attribute codec: patch budget exceeded');applyPatches(read(s.exceptions),new Uint32Array(out.buffer))}return out;
 }
 if(recipe.componentType===5126)throw Error('Attribute codec: invalid integer component');const limits:Record<number,[number,number]>={5120:[-128,127],5121:[0,255],5122:[-32768,32767],5123:[0,65535],5125:[0,4294967295]},[min,max]=limits[recipe.componentType]!;const out=new C(values)as AttributeArray;for(let i=0;i<values;i++)out[i]=integer(q[i],min,max,'decoded component');return out;
}
