/*! Octahedral transform portions derived from Google Draco 1.5.7.
 * Copyright 2016 The Draco Authors. SPDX-License-Identifier: Apache-2.0
 * https://www.apache.org/licenses/LICENSE-2.0
 */
/** Exact octahedral reconstruction, with original-word residual patches.
 * Transform convention reference: Google Draco 1.5.7 OctahedronToolBox,
 * https://github.com/google/draco/blob/1.5.7/src/draco/compression/attributes/normal_compression_utils.h
 * The transform is adapted below with explicit IEEE754 rounding and exact-word validation.
 * Input eligibility and grid precision are inferred from values, never asset metadata/names.
 */
import{encodeAttribute as encodeFallback,decodeAttribute as decodeFallback}from'./asset-attribute-codec-v3.ts';
import type{AttributeInput,AttributeArray,AttributeRecipe as FallbackRecipe,AttributeBuffer,AttributeMetrics as FallbackMetrics}from'./asset-attribute-codec-v3.ts';
import{encodeBuffer,decodeBuffer}from'./asset-buffer-codec.ts';
const MAX_ROWS=1048576,MAX_BYTES=67108864,f=Math.fround;
type OctRecipe={version:3;componentType:5126;type:'VEC3'|'VEC4';count:number;normalized:boolean;storage:{kind:'octahedral-f32';bits:number;predictor:0|1;pairs:AttributeBuffer;exceptions?:AttributeBuffer;fourth?:AttributeBuffer}};
export type OctahedralAttributeRecipe=OctRecipe;
export type{AttributeInput,AttributeArray,AttributeBuffer}from'./asset-attribute-codec-v3.ts';
export type AttributeRecipe=FallbackRecipe|OctRecipe;
export interface AttributeMetrics extends Omit<FallbackMetrics,'candidates'>{candidates:Array<FallbackMetrics['candidates'][number]&{bits?:number}>;octahedral?:{bits:number;vectorCount:number;exactWordsWithoutPatches:number;patchWords:number}}
const scratch=new DataView(new ArrayBuffer(4));
function word(x:number):number{scratch.setFloat32(0,x,true);return scratch.getUint32(0,true)}
function value(bits:number):number{scratch.setUint32(0,bits,true);return scratch.getFloat32(0,true)}
/** Correct the initial approximation against exactly representable midpoint squares.
 * This yields a correctly rounded Float32 root even if a JS engine differs in the
 * last Float64 Math.sqrt bit. Inputs here are finite positive Float32 values.
 */
function sqrt32(n:number):number{let bits=word(Math.sqrt(n));for(let i=0;i<4;i++){const current=value(bits),lower=(current+value(bits-1))/2,upper=(current+value(bits+1))/2,lo=lower*lower,hi=upper*upper;if(n<lo||(n===lo&&(bits&1))){bits--;continue}if(n>hi||(n===hi&&(bits&1))){bits++;continue}return current}throw Error('Normal codec: square-root rounding failure')}
function octDecode(s:number,t:number,bits:number):number[]{const scale=f(2/(2**bits-2));let y=f(f(s*scale)-1),z=f(f(t*scale)-1),x=f(f(1-Math.abs(y))-Math.abs(z)),offset=-x;if(offset<0)offset=0;y=f(y+(y<0?offset:-offset));z=f(z+(z<0?offset:-offset));const norm=f(f(f(x*x)+f(y*y))+f(z*z));if(norm<1e-6)return[0,0,0];const d=f(1/sqrt32(norm));return[f(x*d),f(y*d),f(z*d)]}
function octEncode(x:number,y:number,z:number,bits:number):number[]{const maximum=2**bits-2,center=maximum/2,sum=Math.abs(x)+Math.abs(y)+Math.abs(z);if(!Number.isFinite(sum))return[center,center];const scale=sum>1e-6?1/sum:0;let a=Math.floor((scale?x*scale:1)*center+.5),b=Math.floor(y*scale*center+.5),c=center-Math.abs(a)-Math.abs(b);if(c<0){b+=b>0?c:-c;c=0}if(z*scale<0)c=-c;let s=a>=0?b+center:b<0?Math.abs(c):maximum-Math.abs(c),t=a>=0?c+center:c<0?Math.abs(b):maximum-Math.abs(b);if((s===0&&t===0)||(s===0&&t===maximum)||(s===maximum&&t===0)){s=maximum;t=maximum}else if(s===0&&t>center)t=maximum-t;else if(s===maximum&&t<center)t=maximum-t;else if(t===maximum&&s<center)s=maximum-s;else if(t===0&&s>center)s=maximum-s;return[s,t]}
function buffer(bytes:Uint8Array,hints?:{stride:number;componentBytes:number}):AttributeBuffer{const r=encodeBuffer(bytes,hints);return{codec:r.codec,parameters:r.parameters,sourceLength:r.sourceLength,data:r.data}}
function cost(recipe:AttributeRecipe){let payloadBytes=0;const metadata=JSON.stringify(recipe,(_key,v)=>{if(v instanceof Uint8Array){payloadBytes+=v.length;return{$binaryLength:v.length}}return v}),metadataBytes=new TextEncoder().encode(metadata).length;return{payloadBytes,metadataBytes,total:payloadBytes+metadataBytes}}
function pack(pairs:Uint32Array,bits:number,predictor:0|1):Uint8Array{const out=new Uint8Array(Math.ceil(pairs.length*bits/8)),mask=2**bits-1,half=2**(bits-1);let bit=0;for(let i=0;i<pairs.length;i++){let v=pairs[i]!;if(predictor){let d=(v-(i>=2?pairs[i-2]!:0))&mask;if(d>=half)d-=mask+1;v=d<0?-2*d-1:2*d}let offset=0,remaining=bits;while(remaining){const lane=bit%8,take=Math.min(8-lane,remaining);out[Math.floor(bit/8)]!|=((v>>>offset)&((1<<take)-1))<<lane;bit+=take;offset+=take;remaining-=take}}return out}
function unpack(bytes:Uint8Array,bits:number,count:number,predictor:0|1):Uint32Array{if(bytes.length!==Math.ceil(count*bits/8))throw Error('Normal codec: invalid pair extent');const out=new Uint32Array(count),mask=2**bits-1;let bit=0;for(let i=0;i<count;i++){let v=0,remaining=bits,offset=0;while(remaining){const lane=bit%8,take=Math.min(8-lane,remaining);v+=((bytes[Math.floor(bit/8)]!>>>lane)&((1<<take)-1))*2**offset;bit+=take;offset+=take;remaining-=take}out[i]=predictor?((i>=2?out[i-2]!:0)+(v%2?-(v+1)/2:v/2))&mask:v;if(out[i]!>mask-1)throw Error('Normal codec: octahedral coordinate out of range')}if(bit%8&&bytes.length&&(bytes[bytes.length-1]!>>>(bit%8)))throw Error('Normal codec: nonzero padding bits');return out}
function patchBytes(indices:number[],words:Uint32Array):Uint8Array{const a:number[]=[];let previous=-1;for(const index of indices){let d=index-previous;previous=index;while(d>=128){a.push((d&127)|128);d=Math.floor(d/128)}a.push(d);const w=words[index]!;a.push(w&255,w>>>8&255,w>>>16&255,w>>>24)}return new Uint8Array(a)}
function patch(bytes:Uint8Array,words:Uint32Array,width:number){let cursor=0,previous=-1;while(cursor<bytes.length){let d=0,shift=0,b=0;do{if(cursor>=bytes.length||shift>=35)throw Error('Normal codec: invalid patch');b=bytes[cursor++]!;d+=(b&127)*2**shift;shift+=7}while(b&128);if(!Number.isSafeInteger(d)||d<1||previous+d>=words.length||cursor+4>bytes.length)throw Error('Normal codec: patch out of range');previous+=d;if(previous%width===3)throw Error('Normal codec: patch overlaps preserved fourth lane');words[previous]=(bytes[cursor]!|bytes[cursor+1]!<<8|bytes[cursor+2]!<<16|bytes[cursor+3]!<<24)>>>0;cursor+=4}}
function validInteger(x:unknown,min:number,max:number,label:string):number{if(typeof x!=='number'||!Number.isSafeInteger(x)||x<min||x>max)throw Error('Normal codec: invalid '+label);return x}
export function encodeAttribute(input:AttributeInput):{recipe:AttributeRecipe;metrics:AttributeMetrics}{
 const fallback=encodeFallback(input);if(input.componentType!==5126||(input.type!=='VEC3'&&input.type!=='VEC4')||input.count<16||input.count>MAX_ROWS)return fallback;
 const source=input.array as Float32Array,words=new Uint32Array(source.buffer,source.byteOffset,source.length),width=input.type==='VEC3'?3:4,samples=Math.min(input.count,128),rows=Array.from({length:samples},(_,i)=>Math.floor(i*(input.count-1)/(samples-1)));let units=0;
 for(const row of rows){const p=row*width,x=source[p]!,y=source[p+1]!,z=source[p+2]!;if(Number.isFinite(x+y+z)&&Math.abs(x*x+y*y+z*z-1)<1e-4)units++}if(units<samples*.875)return fallback;
 const probes:Array<{bits:number;estimate:number}>=[];for(let bits=2;bits<=16;bits++){let exceptions=0;for(const row of rows){const p=row*width,pair=octEncode(source[p]!,source[p+1]!,source[p+2]!,bits),decoded=octDecode(pair[0]!,pair[1]!,bits);for(let k=0;k<3;k++)if(word(decoded[k]!)!==words[p+k])exceptions++}if(exceptions<=samples*3/8)probes.push({bits,estimate:input.count*bits/4+input.count*exceptions/samples*5})}
 probes.sort((a,b)=>a.estimate-b.estimate||a.bits-b.bits);if(!probes.length)return fallback;
 let recipe:AttributeRecipe=fallback.recipe,metrics:AttributeMetrics={...fallback.metrics,candidates:[...fallback.metrics.candidates]},best=cost(recipe).total;
 let fourth:AttributeBuffer|undefined;if(width===4){const data=new Uint8Array(input.count*4),view=new DataView(data.buffer);for(let i=0;i<input.count;i++)view.setUint32(i*4,words[i*4+3]!,true);fourth=buffer(data,{stride:4,componentBytes:4})}
 for(const{bits}of probes.slice(0,2)){const pairs=new Uint32Array(input.count*2),exceptions:number[]=[];let eligible=true;for(let row=0;row<input.count;row++){const p=row*width,pair=octEncode(source[p]!,source[p+1]!,source[p+2]!,bits);pairs.set(pair,row*2);const decoded=octDecode(pair[0]!,pair[1]!,bits);for(let k=0;k<3;k++)if(word(decoded[k]!)!==words[p+k])exceptions.push(p+k);if(exceptions.length>Math.min(input.count*3/8,262144)){eligible=false;break}}if(!eligible)continue;const patches=exceptions.length?buffer(patchBytes(exceptions,words)):undefined;for(const predictor of[0,1]as const){const candidate:OctRecipe={version:3,componentType:5126,type:input.type,count:input.count,normalized:input.normalized,storage:{kind:'octahedral-f32',bits,predictor,pairs:buffer(pack(pairs,bits,predictor)),...(patches?{exceptions:patches}:{}),...(fourth?{fourth}:{})}},c=cost(candidate);metrics.candidates.push({kind:'octahedral-f32',bits,predictor,bytes:c.total});if(c.total<best){recipe=candidate;best=c.total;metrics={...metrics,selected:'octahedral-f32',recipeBytes:c.total,payloadBytes:c.payloadBytes,metadataBytes:c.metadataBytes,exceptionCount:exceptions.length,octahedral:{bits,vectorCount:input.count,exactWordsWithoutPatches:input.count*3-exceptions.length,patchWords:exceptions.length}}}}}
 if(recipe.storage.kind==='octahedral-f32'){const replay=decodeAttribute(recipe),actual=new Uint32Array(replay.buffer,replay.byteOffset,replay.length);if(actual.length!==words.length||actual.some((v,i)=>v!==words[i]))throw Error('Normal codec: internal exactness validation failed')}
 return{recipe,metrics};
}
export function decodeAttribute(recipe:AttributeRecipe):AttributeArray{
 if(recipe?.storage?.kind!=='octahedral-f32')return decodeFallback(recipe as FallbackRecipe);const r=recipe as OctRecipe,s=r.storage;if(r.version!==3||r.componentType!==5126||(r.type!=='VEC3'&&r.type!=='VEC4')||typeof r.normalized!=='boolean')throw Error('Normal codec: invalid descriptor');const count=validInteger(r.count,1,MAX_ROWS,'count'),bits=validInteger(s.bits,2,16,'bits'),predictor=validInteger(s.predictor,0,1,'predictor')as 0|1,width=r.type==='VEC3'?3:4;
 const read=(b:AttributeBuffer,expected?:number)=>{if(!b||!(b.data instanceof Uint8Array)||(expected!==undefined&&b.sourceLength!==expected))throw Error('Normal codec: payload extent differs');validInteger(b.sourceLength,0,MAX_BYTES,'payload size');return decodeBuffer(b,MAX_BYTES)},pairs=unpack(read(s.pairs,Math.ceil(count*bits/4)),bits,count*2,predictor),out=new Float32Array(count*width),outWords=new Uint32Array(out.buffer);
 for(let row=0;row<count;row++)out.set(octDecode(pairs[row*2]!,pairs[row*2+1]!,bits),row*width);
 if(width===4){if(!s.fourth)throw Error('Normal codec: missing fourth lane');const data=read(s.fourth,count*4),view=new DataView(data.buffer,data.byteOffset,data.byteLength);for(let row=0;row<count;row++)outWords[row*4+3]=view.getUint32(row*4,true)}else if(s.fourth)throw Error('Normal codec: unexpected fourth lane');
 if(s.exceptions){if(s.exceptions.sourceLength>Math.min(MAX_BYTES,count*27))throw Error('Normal codec: patch budget exceeded');patch(read(s.exceptions),outWords,width)}return out;
}
