/** Trusted playback of decoded low-resolution sprite frames. */
function stateOf(asset:any){if(!asset?.raster?.frames?.length||asset.animation?.mode!=='baked-frames')throw Error('Import a raster asset before playback');const r=asset.raster,a=r.animation;let time=0,direction=0,disposed=false;const frame=()=>direction*a.frameCount+(a.duration>0?Math.min(a.frameCount-1,Math.floor((time%a.duration)/a.duration*a.frameCount)):0);const seek=(value:number)=>{if(disposed)throw Error('Sprite player disposed');if(!Number.isFinite(value)||value<0)throw Error('Invalid sprite time');time=value;};const setDirection=(value:number)=>{if(disposed)throw Error('Sprite player disposed');if(!Number.isInteger(value)||value<0||value>=a.directions)throw Error('Invalid sprite direction');direction=value;};return{r,a,frame,seek,setDirection,get time(){return time;},advance:(delta:number)=>{if(disposed)throw Error('Sprite player disposed');if(!Number.isFinite(delta)||delta<0||!Number.isFinite(time+delta))throw Error('Invalid sprite delta');time+=delta;},assertLive:()=>{if(disposed)throw Error('Sprite player disposed');},dispose:()=>{if(disposed)return false;disposed=true;return true;}};}
export function createRasterCanvasPlayer(host:{canvas:any;asset:any}){
 const s=stateOf(host.asset),ctx=host.canvas.getContext('2d');if(!ctx)throw Error('A 2D canvas is required');host.canvas.width=s.r.width;host.canvas.height=s.r.height;if(host.canvas.style)host.canvas.style.imageRendering='pixelated';ctx.imageSmoothingEnabled=false;const pixels=ctx.createImageData(s.r.width,s.r.height);let previous=-1;
 const draw=()=>{s.assertLive();const i=s.frame();if(i!==previous){pixels.data.set(s.r.frames[i]);ctx.putImageData(pixels,0,0);previous=i;}return i;};
 draw();return{asset:host.asset,clips:s.a.sourceClip===null?[]:[{name:s.a.name,duration:s.a.duration}],seek:(time:number)=>{s.seek(time);return draw();},render:(frame:{time?:number;delta?:number;direction?:number}={})=>{if(frame.time!==undefined)s.seek(frame.time);else if(frame.delta!==undefined)s.advance(frame.delta);if(frame.direction!==undefined)s.setDirection(frame.direction);return draw();},setDirection:(direction:number)=>{s.setDirection(direction);return draw();},play:(clip:number|string=0)=>{if(clip!==0&&clip!==s.a.name)throw Error('Unknown raster clip');s.seek(0);draw();},dispose:()=>s.dispose(),get frame(){return s.frame();},get time(){return s.time;}};
}
export function createRasterThreePlayer(host:{THREE:any;renderer:any;scene?:any;asset:any}){
 const{THREE,renderer,asset}=host;if(String(THREE?.REVISION)!=='180'||!renderer?.render)throw Error('Raster player requires Three r180 and a renderer');const s=stateOf(asset),texture=new THREE.DataTexture(s.r.frames[0],s.r.width,s.r.height,THREE.RGBAFormat);texture.minFilter=texture.magFilter=THREE.NearestFilter;texture.generateMipmaps=false;texture.colorSpace=THREE.SRGBColorSpace;texture.flipY=false;texture.repeat.set(1,-1);texture.offset.set(0,1);texture.needsUpdate=true;
 const material=new THREE.SpriteMaterial({map:texture,transparent:true,toneMapped:false,depthWrite:false}),model=new THREE.Sprite(material);model.name=asset.name;model.scale.set(2*s.r.width/s.r.height,2,1);const scene=host.scene??new THREE.Scene();scene.add(model);let previous=0;
 const update=()=>{s.assertLive();const frame=s.frame();if(frame!==previous){texture.image.data=s.r.frames[frame];texture.needsUpdate=true;previous=frame;}};
 const seek=(time:number)=>{s.seek(time);update();},clips=s.a.sourceClip===null?[]:[{name:s.a.name,duration:s.a.duration,tracks:[]}];
 let running=clips.length>0;
 const action={paused:false,enabled:true,timeScale:1,stop(){running=false;seek(0);return action;},reset(){seek(0);action.paused=false;action.enabled=true;return action;},play(){s.assertLive();running=true;return action;},isRunning(){return running&&!action.paused&&action.enabled;}};
 const mixer={timeScale:1,get time(){return s.time;},setTime:seek,update(delta:number){s.assertLive();if(!Number.isFinite(delta)||delta<0)throw Error('Invalid sprite delta');if(action.isRunning()){s.advance(delta*mixer.timeScale*action.timeScale);update();}},stopAllAction:()=>{action.stop();},uncacheRoot:()=>{running=false;},clipAction:(clip:any)=>{if(!clips.includes(clip))throw Error('Unknown raster clip');return action;},getRoot:()=>model};
 const play=(clip:number|string=0)=>{if(clip!==0&&clip!==s.a.name)throw Error('Unknown raster clip');return action.reset().play();};
 const render=(camera:any,frame:{width:number;height:number;time?:number;delta?:number;direction?:number})=>{s.assertLive();for(const n of[frame.width,frame.height])if(!Number.isInteger(n)||n<1||n>16384)throw Error('Invalid sprite viewport');if(frame.time!==undefined)seek(frame.time);else if(frame.delta!==undefined)mixer.update(frame.delta);if(frame.direction!==undefined){s.setDirection(frame.direction);update();}renderer.render(scene,camera);};
 return{asset,scene,model,clips,mixer,play,seek,render,setDirection:(direction:number)=>{s.setDirection(direction);update();},setStyle:()=>{throw Error('Changing a baked raster style requires a new conversion');},dispose:()=>{if(!s.dispose())return;scene.remove(model);texture.dispose();material.dispose();},uniforms:{},style:asset.style,bounds:new THREE.Box3().setFromObject(model),texture};
}
