//! keel-proof: the Rust twin of `@keel-engine/proof` and `@keel-engine/arena`.
//!
//! A provable KEEL simulation is written once in TypeScript (the reference the game shows)
//! and ported onto this crate for its zkVM guest. Everything here reproduces the TypeScript
//! byte for byte: the packed encodings, the portable roll, the public-values envelope, the
//! generic match input / result and the settlement tree. Parity vectors generated by the
//! TypeScript side are the test.
#![no_std]
extern crate alloc;

pub mod arena;
pub mod bytes;
pub mod int;
pub mod roll;
pub mod stepped;

use alloc::vec::Vec;
use sha2::{Digest, Sha256};

pub fn sha256(data: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(data);
    h.finalize().into()
}

/// sha256(utf8(id)): a program's name as the chain sees it ("game/format@1").
pub fn program_id(id: &str) -> [u8; 32] {
    sha256(id.as_bytes())
}

/// The envelope a guest commits: programId ‖ inputDigest ‖ result.
pub fn public_values(program_id: &[u8; 32], input_digest: &[u8; 32], result: &[u8]) -> Vec<u8> {
    let mut v = Vec::with_capacity(64 + result.len());
    v.extend_from_slice(program_id);
    v.extend_from_slice(input_digest);
    v.extend_from_slice(result);
    v
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// Read past the end, a bad magic, an unknown version, trailing bytes.
    Malformed(&'static str),
    /// A witness that isn't the one the input committed to.
    Witness(&'static str),
    /// A run that broke the format contract (spent above stake, a repeated placing...).
    Run(&'static str),
}

pub type Result<T> = core::result::Result<T, Error>;
